# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md_perf_custompattern.ui'
#
# Created: Wed Apr 15 19:05:55 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CustomPatternDialog(object):
    def setupUi(self, CustomPatternDialog):
        CustomPatternDialog.setObjectName(_fromUtf8("CustomPatternDialog"))
        CustomPatternDialog.resize(283, 460)
        self.verticalLayout = QtGui.QVBoxLayout(CustomPatternDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.demand_down_title = QtGui.QLabel(CustomPatternDialog)
        self.demand_down_title.setEnabled(True)
        self.demand_down_title.setMinimumSize(QtCore.QSize(0, 16))
        self.demand_down_title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.demand_down_title.setObjectName(_fromUtf8("demand_down_title"))
        self.verticalLayout.addWidget(self.demand_down_title)
        self.widget = QtGui.QWidget(CustomPatternDialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.endusetype = QtGui.QLineEdit(self.widget)
        self.endusetype.setGeometry(QtCore.QRect(80, 10, 171, 20))
        self.endusetype.setAcceptDrops(False)
        self.endusetype.setReadOnly(True)
        self.endusetype.setObjectName(_fromUtf8("endusetype"))
        self.enduselbl = QtGui.QLabel(self.widget)
        self.enduselbl.setGeometry(QtCore.QRect(10, 13, 71, 16))
        self.enduselbl.setObjectName(_fromUtf8("enduselbl"))
        self.verticalLayout.addWidget(self.widget)
        self.tableWidget = QtGui.QTableWidget(CustomPatternDialog)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(24)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(14, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(15, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(16, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(17, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(18, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(19, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(20, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(21, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(22, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(23, 0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.verticalLayout.addWidget(self.tableWidget)
        self.footer_widget = QtGui.QWidget(CustomPatternDialog)
        self.footer_widget.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_widget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_widget.setObjectName(_fromUtf8("footer_widget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.footer_widget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.button_Box = QtGui.QDialogButtonBox(self.footer_widget)
        self.button_Box.setOrientation(QtCore.Qt.Horizontal)
        self.button_Box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_Box.setObjectName(_fromUtf8("button_Box"))
        self.horizontalLayout_7.addWidget(self.button_Box)
        self.verticalLayout.addWidget(self.footer_widget)

        self.retranslateUi(CustomPatternDialog)
        QtCore.QObject.connect(self.button_Box, QtCore.SIGNAL(_fromUtf8("accepted()")), CustomPatternDialog.accept)
        QtCore.QObject.connect(self.button_Box, QtCore.SIGNAL(_fromUtf8("rejected()")), CustomPatternDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CustomPatternDialog)

    def retranslateUi(self, CustomPatternDialog):
        CustomPatternDialog.setWindowTitle(_translate("CustomPatternDialog", "Dialog", None))
        self.demand_down_title.setText(_translate("CustomPatternDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Define Custom Pattern (24h)</span></p></body></html>", None))
        self.endusetype.setText(_translate("CustomPatternDialog", "<end use type>", None))
        self.enduselbl.setText(_translate("CustomPatternDialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">End Use:</span></p></body></html>", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("CustomPatternDialog", "      00:00      ", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("CustomPatternDialog", "      01:00", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("CustomPatternDialog", "      02:00", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("CustomPatternDialog", "      03:00", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("CustomPatternDialog", "      04:00", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("CustomPatternDialog", "      05:00", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("CustomPatternDialog", "      06:00", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("CustomPatternDialog", "      07:00", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("CustomPatternDialog", "      08:00", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("CustomPatternDialog", "      09:00", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("CustomPatternDialog", "      10:00", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("CustomPatternDialog", "      11:00", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("CustomPatternDialog", "      12:00", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("CustomPatternDialog", "      13:00", None))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("CustomPatternDialog", "      14:00", None))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("CustomPatternDialog", "      15:00", None))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("CustomPatternDialog", "      16:00", None))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("CustomPatternDialog", "      17:00", None))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("CustomPatternDialog", "      18:00", None))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("CustomPatternDialog", "      19:00", None))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("CustomPatternDialog", "      20:00", None))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("CustomPatternDialog", "      21:00", None))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("CustomPatternDialog", "      22:00", None))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("CustomPatternDialog", "      23:00", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CustomPatternDialog", "Scaling Factor", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

