# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'md_perf_stakeholdercost.ui'
#
# Created: Fri Feb 03 10:40:51 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AllocateStakeholders_Dialog(object):
    def setupUi(self, AllocateStakeholders_Dialog):
        AllocateStakeholders_Dialog.setObjectName(_fromUtf8("AllocateStakeholders_Dialog"))
        AllocateStakeholders_Dialog.resize(577, 566)
        self.verticalLayout = QtGui.QVBoxLayout(AllocateStakeholders_Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stakeholder_title = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.stakeholder_title.setEnabled(True)
        self.stakeholder_title.setMinimumSize(QtCore.QSize(0, 16))
        self.stakeholder_title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.stakeholder_title.setObjectName(_fromUtf8("stakeholder_title"))
        self.verticalLayout.addWidget(self.stakeholder_title)
        self.stakeholder_description = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.stakeholder_description.setEnabled(True)
        self.stakeholder_description.setMinimumSize(QtCore.QSize(0, 16))
        self.stakeholder_description.setMaximumSize(QtCore.QSize(16777215, 16))
        self.stakeholder_description.setObjectName(_fromUtf8("stakeholder_description"))
        self.verticalLayout.addWidget(self.stakeholder_description)
        self.stakeholder_manage = QtGui.QWidget(AllocateStakeholders_Dialog)
        self.stakeholder_manage.setMinimumSize(QtCore.QSize(0, 40))
        self.stakeholder_manage.setObjectName(_fromUtf8("stakeholder_manage"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.stakeholder_manage)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stakeholder_lbl = QtGui.QLabel(self.stakeholder_manage)
        self.stakeholder_lbl.setObjectName(_fromUtf8("stakeholder_lbl"))
        self.horizontalLayout_2.addWidget(self.stakeholder_lbl)
        self.stakeholder_box = QtGui.QLineEdit(self.stakeholder_manage)
        self.stakeholder_box.setMaxLength(20)
        self.stakeholder_box.setObjectName(_fromUtf8("stakeholder_box"))
        self.horizontalLayout_2.addWidget(self.stakeholder_box)
        self.stakeholder_add = QtGui.QPushButton(self.stakeholder_manage)
        self.stakeholder_add.setObjectName(_fromUtf8("stakeholder_add"))
        self.horizontalLayout_2.addWidget(self.stakeholder_add)
        self.stakeholder_remove = QtGui.QPushButton(self.stakeholder_manage)
        self.stakeholder_remove.setObjectName(_fromUtf8("stakeholder_remove"))
        self.horizontalLayout_2.addWidget(self.stakeholder_remove)
        self.verticalLayout.addWidget(self.stakeholder_manage)
        self.stakeholder_descript = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.stakeholder_descript.setEnabled(True)
        self.stakeholder_descript.setMinimumSize(QtCore.QSize(0, 16))
        self.stakeholder_descript.setMaximumSize(QtCore.QSize(16777215, 16))
        self.stakeholder_descript.setObjectName(_fromUtf8("stakeholder_descript"))
        self.verticalLayout.addWidget(self.stakeholder_descript)
        self.line = QtGui.QFrame(AllocateStakeholders_Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.cost_alloc_type_title = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.cost_alloc_type_title.setEnabled(True)
        self.cost_alloc_type_title.setMinimumSize(QtCore.QSize(0, 16))
        self.cost_alloc_type_title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.cost_alloc_type_title.setObjectName(_fromUtf8("cost_alloc_type_title"))
        self.verticalLayout.addWidget(self.cost_alloc_type_title)
        self.stakeholder_description_2 = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.stakeholder_description_2.setEnabled(True)
        self.stakeholder_description_2.setMinimumSize(QtCore.QSize(0, 16))
        self.stakeholder_description_2.setMaximumSize(QtCore.QSize(16777215, 16))
        self.stakeholder_description_2.setObjectName(_fromUtf8("stakeholder_description_2"))
        self.verticalLayout.addWidget(self.stakeholder_description_2)
        self.cost_alloc_type_table = QtGui.QTableWidget(AllocateStakeholders_Dialog)
        self.cost_alloc_type_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.cost_alloc_type_table.setObjectName(_fromUtf8("cost_alloc_type_table"))
        self.cost_alloc_type_table.setColumnCount(4)
        self.cost_alloc_type_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.cost_alloc_type_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.cost_alloc_type_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.cost_alloc_type_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.cost_alloc_type_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.cost_alloc_type_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.cost_alloc_type_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.cost_alloc_type_table)
        self.cost_alloc_type_widget = QtGui.QWidget(AllocateStakeholders_Dialog)
        self.cost_alloc_type_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.cost_alloc_type_widget.setObjectName(_fromUtf8("cost_alloc_type_widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.cost_alloc_type_widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cost_alloc_type_lbl = QtGui.QLabel(self.cost_alloc_type_widget)
        self.cost_alloc_type_lbl.setObjectName(_fromUtf8("cost_alloc_type_lbl"))
        self.horizontalLayout_3.addWidget(self.cost_alloc_type_lbl)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.cost_alloc_type_boxcheck = QtGui.QLineEdit(self.cost_alloc_type_widget)
        self.cost_alloc_type_boxcheck.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cost_alloc_type_boxcheck.setAcceptDrops(False)
        self.cost_alloc_type_boxcheck.setReadOnly(True)
        self.cost_alloc_type_boxcheck.setObjectName(_fromUtf8("cost_alloc_type_boxcheck"))
        self.horizontalLayout_3.addWidget(self.cost_alloc_type_boxcheck)
        self.cost_alloc_type_reset = QtGui.QPushButton(self.cost_alloc_type_widget)
        self.cost_alloc_type_reset.setObjectName(_fromUtf8("cost_alloc_type_reset"))
        self.horizontalLayout_3.addWidget(self.cost_alloc_type_reset)
        self.verticalLayout.addWidget(self.cost_alloc_type_widget)
        self.line_2 = QtGui.QFrame(AllocateStakeholders_Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.cost_alloc_scale_title = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.cost_alloc_scale_title.setEnabled(True)
        self.cost_alloc_scale_title.setMinimumSize(QtCore.QSize(0, 16))
        self.cost_alloc_scale_title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.cost_alloc_scale_title.setObjectName(_fromUtf8("cost_alloc_scale_title"))
        self.verticalLayout.addWidget(self.cost_alloc_scale_title)
        self.stakeholder_description_3 = QtGui.QLabel(AllocateStakeholders_Dialog)
        self.stakeholder_description_3.setEnabled(True)
        self.stakeholder_description_3.setMinimumSize(QtCore.QSize(0, 16))
        self.stakeholder_description_3.setMaximumSize(QtCore.QSize(16777215, 16))
        self.stakeholder_description_3.setObjectName(_fromUtf8("stakeholder_description_3"))
        self.verticalLayout.addWidget(self.stakeholder_description_3)
        self.cost_alloc_scale_table = QtGui.QTableWidget(AllocateStakeholders_Dialog)
        self.cost_alloc_scale_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.cost_alloc_scale_table.setObjectName(_fromUtf8("cost_alloc_scale_table"))
        self.cost_alloc_scale_table.setColumnCount(4)
        self.cost_alloc_scale_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.cost_alloc_scale_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.cost_alloc_scale_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cost_alloc_scale_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cost_alloc_scale_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cost_alloc_scale_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.cost_alloc_scale_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.cost_alloc_scale_table)
        self.cost_alloc_scale_widget = QtGui.QWidget(AllocateStakeholders_Dialog)
        self.cost_alloc_scale_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.cost_alloc_scale_widget.setObjectName(_fromUtf8("cost_alloc_scale_widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.cost_alloc_scale_widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cost_alloc_scale_lbl = QtGui.QLabel(self.cost_alloc_scale_widget)
        self.cost_alloc_scale_lbl.setObjectName(_fromUtf8("cost_alloc_scale_lbl"))
        self.horizontalLayout.addWidget(self.cost_alloc_scale_lbl)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cost_alloc_scale_boxcheck = QtGui.QLineEdit(self.cost_alloc_scale_widget)
        self.cost_alloc_scale_boxcheck.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cost_alloc_scale_boxcheck.setAcceptDrops(False)
        self.cost_alloc_scale_boxcheck.setReadOnly(True)
        self.cost_alloc_scale_boxcheck.setObjectName(_fromUtf8("cost_alloc_scale_boxcheck"))
        self.horizontalLayout.addWidget(self.cost_alloc_scale_boxcheck)
        self.cost_alloc_scale_reset = QtGui.QPushButton(self.cost_alloc_scale_widget)
        self.cost_alloc_scale_reset.setObjectName(_fromUtf8("cost_alloc_scale_reset"))
        self.horizontalLayout.addWidget(self.cost_alloc_scale_reset)
        self.verticalLayout.addWidget(self.cost_alloc_scale_widget)
        self.footer_widget = QtGui.QWidget(AllocateStakeholders_Dialog)
        self.footer_widget.setMinimumSize(QtCore.QSize(0, 38))
        self.footer_widget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer_widget.setObjectName(_fromUtf8("footer_widget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.footer_widget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.button_Box = QtGui.QDialogButtonBox(self.footer_widget)
        self.button_Box.setOrientation(QtCore.Qt.Horizontal)
        self.button_Box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_Box.setObjectName(_fromUtf8("button_Box"))
        self.horizontalLayout_7.addWidget(self.button_Box)
        self.verticalLayout.addWidget(self.footer_widget)

        self.retranslateUi(AllocateStakeholders_Dialog)
        QtCore.QObject.connect(self.button_Box, QtCore.SIGNAL(_fromUtf8("accepted()")), AllocateStakeholders_Dialog.accept)
        QtCore.QObject.connect(self.button_Box, QtCore.SIGNAL(_fromUtf8("rejected()")), AllocateStakeholders_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AllocateStakeholders_Dialog)

    def retranslateUi(self, AllocateStakeholders_Dialog):
        AllocateStakeholders_Dialog.setWindowTitle(_translate("AllocateStakeholders_Dialog", "Define and Allocate Stakeholder Costs", None))
        self.stakeholder_title.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Stakeholder Cost Matrix</span></p></body></html>", None))
        self.stakeholder_description.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Customize different levels of responsibilities for different stakeholders.</p></body></html>", None))
        self.stakeholder_lbl.setText(_translate("AllocateStakeholders_Dialog", "<html><head/><body><p>Stakeholder Name (20 chars max): </p></body></html>", None))
        self.stakeholder_add.setText(_translate("AllocateStakeholders_Dialog", "Add", None))
        self.stakeholder_remove.setText(_translate("AllocateStakeholders_Dialog", "Remove", None))
        self.stakeholder_descript.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">(to remove stakeholder name, either click on the name in the table or type the name and click remove)</span></p></body></html>", None))
        self.cost_alloc_type_title.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Cost Allocation by Cost Type [%]</span></p></body></html>", None))
        self.stakeholder_description_2.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter percentages under the four basic life cycle cost items, ensure that columns add up to 100%</p></body></html>", None))
        item = self.cost_alloc_type_table.verticalHeaderItem(0)
        item.setText(_translate("AllocateStakeholders_Dialog", "Default Stakeholder ", None))
        item = self.cost_alloc_type_table.verticalHeaderItem(1)
        item.setText(_translate("AllocateStakeholders_Dialog", "TOTALS", None))
        item = self.cost_alloc_type_table.horizontalHeaderItem(0)
        item.setText(_translate("AllocateStakeholders_Dialog", "Capital", None))
        item = self.cost_alloc_type_table.horizontalHeaderItem(1)
        item.setText(_translate("AllocateStakeholders_Dialog", "Maintenance", None))
        item = self.cost_alloc_type_table.horizontalHeaderItem(2)
        item.setText(_translate("AllocateStakeholders_Dialog", "Renewal", None))
        item = self.cost_alloc_type_table.horizontalHeaderItem(3)
        item.setText(_translate("AllocateStakeholders_Dialog", "Decommisioning", None))
        self.cost_alloc_type_lbl.setText(_translate("AllocateStakeholders_Dialog", "<html><head/><body><p>% of Costs Responsibility Allocated based on Cost Type: </p></body></html>", None))
        self.cost_alloc_type_boxcheck.setText(_translate("AllocateStakeholders_Dialog", "100%", None))
        self.cost_alloc_type_reset.setText(_translate("AllocateStakeholders_Dialog", "Reset Table", None))
        self.cost_alloc_scale_title.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Cost Allocation by Asset Scale [%]</span></p></body></html>", None))
        self.stakeholder_description_3.setText(_translate("AllocateStakeholders_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter percentages under the four spatial scales, ensure that columns add up to 100%</p></body></html>", None))
        item = self.cost_alloc_scale_table.verticalHeaderItem(0)
        item.setText(_translate("AllocateStakeholders_Dialog", "Default Stakeholder", None))
        item = self.cost_alloc_scale_table.verticalHeaderItem(1)
        item.setText(_translate("AllocateStakeholders_Dialog", "TOTALS", None))
        item = self.cost_alloc_scale_table.horizontalHeaderItem(0)
        item.setText(_translate("AllocateStakeholders_Dialog", "Allotment", None))
        item = self.cost_alloc_scale_table.horizontalHeaderItem(1)
        item.setText(_translate("AllocateStakeholders_Dialog", "Street-scape", None))
        item = self.cost_alloc_scale_table.horizontalHeaderItem(2)
        item.setText(_translate("AllocateStakeholders_Dialog", "Neighbourhood", None))
        item = self.cost_alloc_scale_table.horizontalHeaderItem(3)
        item.setText(_translate("AllocateStakeholders_Dialog", "Regional", None))
        self.cost_alloc_scale_lbl.setText(_translate("AllocateStakeholders_Dialog", "<html><head/><body><p>% of Costs Responsibility allocated based on scale of asset: </p></body></html>", None))
        self.cost_alloc_scale_boxcheck.setText(_translate("AllocateStakeholders_Dialog", "100%", None))
        self.cost_alloc_scale_reset.setText(_translate("AllocateStakeholders_Dialog", "Reset Table", None))

