# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesdialog.ui'
#
# Created: Tue Apr 29 15:13:39 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName(_fromUtf8("PreferencesDialog"))
        PreferencesDialog.resize(480, 640)
        PreferencesDialog.setWindowTitle(QtGui.QApplication.translate("PreferencesDialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(PreferencesDialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.preferences_cogs = QtGui.QLabel(self.widget)
        self.preferences_cogs.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.preferences_cogs.setMinimumSize(QtCore.QSize(50, 50))
        self.preferences_cogs.setMaximumSize(QtCore.QSize(50, 50))
        self.preferences_cogs.setText(_fromUtf8(""))
        self.preferences_cogs.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/bevel-gear-icon.png")))
        self.preferences_cogs.setObjectName(_fromUtf8("preferences_cogs"))
        self.dbtitle = QtGui.QLabel(self.widget)
        self.dbtitle.setGeometry(QtCore.QRect(55, 5, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dbtitle.setFont(font)
        self.dbtitle.setText(QtGui.QApplication.translate("PreferencesDialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.dbtitle.setObjectName(_fromUtf8("dbtitle"))
        self.dbsubtitle = QtGui.QLabel(self.widget)
        self.dbsubtitle.setGeometry(QtCore.QRect(55, 25, 361, 20))
        self.dbsubtitle.setText(QtGui.QApplication.translate("PreferencesDialog", "Configure the program, simulation options, paths and export options.", None, QtGui.QApplication.UnicodeUTF8))
        self.dbsubtitle.setObjectName(_fromUtf8("dbsubtitle"))
        self.verticalLayout.addWidget(self.widget)
        self.main_preferences_widget = QtGui.QWidget(PreferencesDialog)
        self.main_preferences_widget.setObjectName(_fromUtf8("main_preferences_widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.main_preferences_widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.options_tabs = QtGui.QTabWidget(self.main_preferences_widget)
        self.options_tabs.setObjectName(_fromUtf8("options_tabs"))
        self.general_tab = QtGui.QWidget()
        self.general_tab.setObjectName(_fromUtf8("general_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.general_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.general_tab)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 401, 458))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_2 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.projinfo_options = QtGui.QLabel(self.widget_2)
        self.projinfo_options.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.projinfo_options.setText(QtGui.QApplication.translate("PreferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Project Details</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.projinfo_options.setObjectName(_fromUtf8("projinfo_options"))
        self.modeller_name_lbl = QtGui.QLabel(self.widget_2)
        self.modeller_name_lbl.setGeometry(QtCore.QRect(20, 40, 141, 16))
        self.modeller_name_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Default Modeller Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.modeller_name_lbl.setObjectName(_fromUtf8("modeller_name_lbl"))
        self.modeller_name_box = QtGui.QLineEdit(self.widget_2)
        self.modeller_name_box.setGeometry(QtCore.QRect(160, 40, 181, 20))
        self.modeller_name_box.setObjectName(_fromUtf8("modeller_name_box"))
        self.modeller_affil_lbl = QtGui.QLabel(self.widget_2)
        self.modeller_affil_lbl.setGeometry(QtCore.QRect(20, 70, 141, 16))
        self.modeller_affil_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Default Affiliation:", None, QtGui.QApplication.UnicodeUTF8))
        self.modeller_affil_lbl.setObjectName(_fromUtf8("modeller_affil_lbl"))
        self.modeller_affil_box = QtGui.QLineEdit(self.widget_2)
        self.modeller_affil_box.setGeometry(QtCore.QRect(160, 70, 181, 20))
        self.modeller_affil_box.setObjectName(_fromUtf8("modeller_affil_box"))
        self.verticalLayout_6.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.options_tabs.addTab(self.general_tab, _fromUtf8(""))
        self.simulation_tab = QtGui.QWidget()
        self.simulation_tab.setObjectName(_fromUtf8("simulation_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.simulation_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scrollArea_2 = QtGui.QScrollArea(self.simulation_tab)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 401, 504))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_5 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.techplan_options = QtGui.QLabel(self.widget_5)
        self.techplan_options.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.techplan_options.setText(QtGui.QApplication.translate("PreferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Technologies Planning</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_options.setObjectName(_fromUtf8("techplan_options"))
        self.techplan_city_lbl = QtGui.QLabel(self.widget_5)
        self.techplan_city_lbl.setGeometry(QtCore.QRect(20, 70, 141, 16))
        self.techplan_city_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Default City:", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_city_lbl.setObjectName(_fromUtf8("techplan_city_lbl"))
        self.tech_leaveempty_radio = QtGui.QRadioButton(self.widget_5)
        self.tech_leaveempty_radio.setGeometry(QtCore.QRect(220, 100, 151, 18))
        self.tech_leaveempty_radio.setText(QtGui.QApplication.translate("PreferencesDialog", "Leave Basin Empty", None, QtGui.QApplication.UnicodeUTF8))
        self.tech_leaveempty_radio.setObjectName(_fromUtf8("tech_leaveempty_radio"))
        self.techplan_iter_spin = QtGui.QSpinBox(self.widget_5)
        self.techplan_iter_spin.setGeometry(QtCore.QRect(240, 35, 131, 22))
        self.techplan_iter_spin.setSuffix(QtGui.QApplication.translate("PreferencesDialog", " realisations", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_iter_spin.setMinimum(500)
        self.techplan_iter_spin.setMaximum(10000)
        self.techplan_iter_spin.setSingleStep(500)
        self.techplan_iter_spin.setObjectName(_fromUtf8("techplan_iter_spin"))
        self.techplan_city_combo = QtGui.QComboBox(self.widget_5)
        self.techplan_city_combo.setGeometry(QtCore.QRect(180, 65, 191, 22))
        self.techplan_city_combo.setObjectName(_fromUtf8("techplan_city_combo"))
        self.techplan_city_combo.addItem(_fromUtf8(""))
        self.techplan_city_combo.setItemText(0, QtGui.QApplication.translate("PreferencesDialog", "Adelaide", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_city_combo.addItem(_fromUtf8(""))
        self.techplan_city_combo.setItemText(1, QtGui.QApplication.translate("PreferencesDialog", "Brisbane", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_city_combo.addItem(_fromUtf8(""))
        self.techplan_city_combo.setItemText(2, QtGui.QApplication.translate("PreferencesDialog", "Darwin", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_city_combo.addItem(_fromUtf8(""))
        self.techplan_city_combo.setItemText(3, QtGui.QApplication.translate("PreferencesDialog", "Melbourne", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_city_combo.addItem(_fromUtf8(""))
        self.techplan_city_combo.setItemText(4, QtGui.QApplication.translate("PreferencesDialog", "Perth", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_city_combo.addItem(_fromUtf8(""))
        self.techplan_city_combo.setItemText(5, QtGui.QApplication.translate("PreferencesDialog", "Sydney", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_decision_lbl = QtGui.QLabel(self.widget_5)
        self.techplan_decision_lbl.setGeometry(QtCore.QRect(20, 100, 201, 16))
        self.techplan_decision_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Decision to make if no solutions found:", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_decision_lbl.setObjectName(_fromUtf8("techplan_decision_lbl"))
        self.techplan_iter_lbl = QtGui.QLabel(self.widget_5)
        self.techplan_iter_lbl.setGeometry(QtCore.QRect(20, 40, 201, 16))
        self.techplan_iter_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Default Monte Carlo Iteration Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_iter_lbl.setObjectName(_fromUtf8("techplan_iter_lbl"))
        self.tech_highest_radio = QtGui.QRadioButton(self.widget_5)
        self.tech_highest_radio.setGeometry(QtCore.QRect(220, 120, 151, 18))
        self.tech_highest_radio.setText(QtGui.QApplication.translate("PreferencesDialog", "Choose Highest Service", None, QtGui.QApplication.UnicodeUTF8))
        self.tech_highest_radio.setObjectName(_fromUtf8("tech_highest_radio"))
        self.techplan_strats_spin = QtGui.QSpinBox(self.widget_5)
        self.techplan_strats_spin.setGeometry(QtCore.QRect(240, 145, 131, 22))
        self.techplan_strats_spin.setSuffix(QtGui.QApplication.translate("PreferencesDialog", " strategies", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_strats_spin.setMinimum(0)
        self.techplan_strats_spin.setMaximum(10)
        self.techplan_strats_spin.setSingleStep(1)
        self.techplan_strats_spin.setProperty("value", 5)
        self.techplan_strats_spin.setObjectName(_fromUtf8("techplan_strats_spin"))
        self.techplan_strats_lbl1 = QtGui.QLabel(self.widget_5)
        self.techplan_strats_lbl1.setGeometry(QtCore.QRect(20, 150, 201, 16))
        self.techplan_strats_lbl1.setText(QtGui.QApplication.translate("PreferencesDialog", "Number of chosen strategies to export:", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_strats_lbl1.setObjectName(_fromUtf8("techplan_strats_lbl1"))
        self.techplan_strats_lbl2 = QtGui.QLabel(self.widget_5)
        self.techplan_strats_lbl2.setGeometry(QtCore.QRect(20, 170, 201, 16))
        self.techplan_strats_lbl2.setText(QtGui.QApplication.translate("PreferencesDialog", "(static simulations only)", None, QtGui.QApplication.UnicodeUTF8))
        self.techplan_strats_lbl2.setObjectName(_fromUtf8("techplan_strats_lbl2"))
        self.verticalLayout_7.addWidget(self.widget_5)
        self.widget_3 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 280))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.perf_musicpath_box = QtGui.QLineEdit(self.widget_3)
        self.perf_musicpath_box.setEnabled(False)
        self.perf_musicpath_box.setGeometry(QtCore.QRect(160, 90, 141, 20))
        self.perf_musicpath_box.setObjectName(_fromUtf8("perf_musicpath_box"))
        self.perf_musicpath_lbl = QtGui.QLabel(self.widget_3)
        self.perf_musicpath_lbl.setGeometry(QtCore.QRect(50, 90, 141, 16))
        self.perf_musicpath_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Path to MUSIC.exe:", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_musicpath_lbl.setObjectName(_fromUtf8("perf_musicpath_lbl"))
        self.perf_tte_check = QtGui.QCheckBox(self.widget_3)
        self.perf_tte_check.setEnabled(False)
        self.perf_tte_check.setGeometry(QtCore.QRect(70, 180, 221, 18))
        self.perf_tte_check.setText(QtGui.QApplication.translate("PreferencesDialog", "Treatment Train Effectiveness", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_tte_check.setObjectName(_fromUtf8("perf_tte_check"))
        self.perf_musicpath_browse = QtGui.QPushButton(self.widget_3)
        self.perf_musicpath_browse.setEnabled(False)
        self.perf_musicpath_browse.setGeometry(QtCore.QRect(310, 90, 61, 23))
        self.perf_musicpath_browse.setText(QtGui.QApplication.translate("PreferencesDialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_musicpath_browse.setObjectName(_fromUtf8("perf_musicpath_browse"))
        self.perf_musicver_lbl = QtGui.QLabel(self.widget_3)
        self.perf_musicver_lbl.setGeometry(QtCore.QRect(50, 120, 141, 16))
        self.perf_musicver_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "MUSIC Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_musicver_lbl.setObjectName(_fromUtf8("perf_musicver_lbl"))
        self.perf_export_lbl = QtGui.QLabel(self.widget_3)
        self.perf_export_lbl.setGeometry(QtCore.QRect(50, 150, 141, 16))
        self.perf_export_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Select Results to Export:", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_export_lbl.setObjectName(_fromUtf8("perf_export_lbl"))
        self.perf_musicvercombo = QtGui.QComboBox(self.widget_3)
        self.perf_musicvercombo.setEnabled(False)
        self.perf_musicvercombo.setGeometry(QtCore.QRect(160, 120, 211, 22))
        self.perf_musicvercombo.setObjectName(_fromUtf8("perf_musicvercombo"))
        self.perf_musicvercombo.addItem(_fromUtf8(""))
        self.perf_musicvercombo.setItemText(0, QtGui.QApplication.translate("PreferencesDialog", "eWater MUSIC Version 5", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_musicvercombo.addItem(_fromUtf8(""))
        self.perf_musicvercombo.setItemText(1, QtGui.QApplication.translate("PreferencesDialog", "eWater MUSIC Version 6", None, QtGui.QApplication.UnicodeUTF8))
        self.perfassess_options = QtGui.QLabel(self.widget_3)
        self.perfassess_options.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.perfassess_options.setText(QtGui.QApplication.translate("PreferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Performance Assessment</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.perfassess_options.setObjectName(_fromUtf8("perfassess_options"))
        self.perf_musicauto_check = QtGui.QCheckBox(self.widget_3)
        self.perf_musicauto_check.setEnabled(False)
        self.perf_musicauto_check.setGeometry(QtCore.QRect(20, 60, 311, 18))
        self.perf_musicauto_check.setText(QtGui.QApplication.translate("PreferencesDialog", "AutoRun MUSIC Simulation Files", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_musicauto_check.setObjectName(_fromUtf8("perf_musicauto_check"))
        self.perf_flux_check = QtGui.QCheckBox(self.widget_3)
        self.perf_flux_check.setEnabled(False)
        self.perf_flux_check.setGeometry(QtCore.QRect(70, 210, 211, 18))
        self.perf_flux_check.setText(QtGui.QApplication.translate("PreferencesDialog", "Flow and Pollution Time Series", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_flux_check.setObjectName(_fromUtf8("perf_flux_check"))
        self.perf_writeMUSICcheck = QtGui.QCheckBox(self.widget_3)
        self.perf_writeMUSICcheck.setEnabled(True)
        self.perf_writeMUSICcheck.setGeometry(QtCore.QRect(20, 35, 341, 18))
        self.perf_writeMUSICcheck.setText(QtGui.QApplication.translate("PreferencesDialog", "Write MUSIC Simulation Files for output WSUD Strategies", None, QtGui.QApplication.UnicodeUTF8))
        self.perf_writeMUSICcheck.setObjectName(_fromUtf8("perf_writeMUSICcheck"))
        self.verticalLayout_7.addWidget(self.widget_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.options_tabs.addTab(self.simulation_tab, _fromUtf8(""))
        self.results_tab = QtGui.QWidget()
        self.results_tab.setObjectName(_fromUtf8("results_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.results_tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_3 = QtGui.QScrollArea(self.results_tab)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 401, 458))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widget_7 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.style2_radio = QtGui.QRadioButton(self.widget_7)
        self.style2_radio.setGeometry(QtCore.QRect(145, 160, 111, 18))
        self.style2_radio.setText(QtGui.QApplication.translate("PreferencesDialog", "OpenStreetMap", None, QtGui.QApplication.UnicodeUTF8))
        self.style2_radio.setObjectName(_fromUtf8("style2_radio"))
        self.label_17 = QtGui.QLabel(self.widget_7)
        self.label_17.setGeometry(QtCore.QRect(40, 80, 41, 16))
        self.label_17.setText(QtGui.QApplication.translate("PreferencesDialog", "Style1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.results_tileserver_box = QtGui.QLineEdit(self.widget_7)
        self.results_tileserver_box.setGeometry(QtCore.QRect(110, 190, 251, 20))
        self.results_tileserver_box.setObjectName(_fromUtf8("results_tileserver_box"))
        self.label_19 = QtGui.QLabel(self.widget_7)
        self.label_19.setGeometry(QtCore.QRect(310, 80, 41, 16))
        self.label_19.setText(QtGui.QApplication.translate("PreferencesDialog", "Style3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.results_tileserver_lbl = QtGui.QLabel(self.widget_7)
        self.results_tileserver_lbl.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.results_tileserver_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Tile Server URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.results_tileserver_lbl.setObjectName(_fromUtf8("results_tileserver_lbl"))
        self.stylecustom_radio = QtGui.QRadioButton(self.widget_7)
        self.stylecustom_radio.setGeometry(QtCore.QRect(270, 160, 91, 18))
        self.stylecustom_radio.setText(QtGui.QApplication.translate("PreferencesDialog", "Custom Tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.stylecustom_radio.setObjectName(_fromUtf8("stylecustom_radio"))
        self.style1_radio = QtGui.QRadioButton(self.widget_7)
        self.style1_radio.setGeometry(QtCore.QRect(20, 160, 111, 18))
        self.style1_radio.setText(QtGui.QApplication.translate("PreferencesDialog", "OpenStreetMap", None, QtGui.QApplication.UnicodeUTF8))
        self.style1_radio.setObjectName(_fromUtf8("style1_radio"))
        self.label_18 = QtGui.QLabel(self.widget_7)
        self.label_18.setGeometry(QtCore.QRect(180, 80, 41, 16))
        self.label_18.setText(QtGui.QApplication.translate("PreferencesDialog", "Style2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.results_mapstyle_lbl = QtGui.QLabel(self.widget_7)
        self.results_mapstyle_lbl.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.results_mapstyle_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Select Map Viewer Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.results_mapstyle_lbl.setObjectName(_fromUtf8("results_mapstyle_lbl"))
        self.resultsviewer_options = QtGui.QLabel(self.widget_7)
        self.resultsviewer_options.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.resultsviewer_options.setText(QtGui.QApplication.translate("PreferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Results Viewer</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.resultsviewer_options.setObjectName(_fromUtf8("resultsviewer_options"))
        self.widget_8 = QtGui.QWidget(self.widget_7)
        self.widget_8.setGeometry(QtCore.QRect(20, 60, 101, 91))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.widget_9 = QtGui.QWidget(self.widget_7)
        self.widget_9.setGeometry(QtCore.QRect(140, 60, 101, 91))
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.widget_10 = QtGui.QWidget(self.widget_7)
        self.widget_10.setGeometry(QtCore.QRect(260, 60, 101, 91))
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.verticalLayout_8.addWidget(self.widget_7)
        self.widget_6 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.gearth_path_browse = QtGui.QPushButton(self.widget_6)
        self.gearth_path_browse.setGeometry(QtCore.QRect(310, 70, 61, 23))
        self.gearth_path_browse.setText(QtGui.QApplication.translate("PreferencesDialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.gearth_path_browse.setObjectName(_fromUtf8("gearth_path_browse"))
        self.gearth_path_lbl = QtGui.QLabel(self.widget_6)
        self.gearth_path_lbl.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.gearth_path_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "Program Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.gearth_path_lbl.setObjectName(_fromUtf8("gearth_path_lbl"))
        self.gearth_lbl = QtGui.QLabel(self.widget_6)
        self.gearth_lbl.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.gearth_lbl.setText(QtGui.QApplication.translate("PreferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Google Earth</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.gearth_lbl.setObjectName(_fromUtf8("gearth_lbl"))
        self.gearth_auto_check = QtGui.QCheckBox(self.widget_6)
        self.gearth_auto_check.setGeometry(QtCore.QRect(110, 100, 251, 18))
        self.gearth_auto_check.setText(QtGui.QApplication.translate("PreferencesDialog", "Automatically load Earth Maps upon export", None, QtGui.QApplication.UnicodeUTF8))
        self.gearth_auto_check.setObjectName(_fromUtf8("gearth_auto_check"))
        self.gearth_get = QtGui.QPushButton(self.widget_6)
        self.gearth_get.setGeometry(QtCore.QRect(10, 40, 121, 23))
        self.gearth_get.setText(QtGui.QApplication.translate("PreferencesDialog", "Get Google Earth", None, QtGui.QApplication.UnicodeUTF8))
        self.gearth_get.setObjectName(_fromUtf8("gearth_get"))
        self.gearth_path_box = QtGui.QLineEdit(self.widget_6)
        self.gearth_path_box.setGeometry(QtCore.QRect(110, 70, 191, 20))
        self.gearth_path_box.setObjectName(_fromUtf8("gearth_path_box"))
        self.verticalLayout_8.addWidget(self.widget_6)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea_3)
        self.options_tabs.addTab(self.results_tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.options_tabs)
        self.verticalLayout.addWidget(self.main_preferences_widget)
        self.widget_4 = QtGui.QWidget(PreferencesDialog)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 38))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 38))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.remarks = QtGui.QLabel(self.widget_4)
        self.remarks.setText(QtGui.QApplication.translate("PreferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic;\">UrbanBEATS.preferences</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.remarks.setObjectName(_fromUtf8("remarks"))
        self.horizontalLayout_2.addWidget(self.remarks)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget_4)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.optionsReset_button = QtGui.QPushButton(self.widget_4)
        self.optionsReset_button.setText(QtGui.QApplication.translate("PreferencesDialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsReset_button.setObjectName(_fromUtf8("optionsReset_button"))
        self.horizontalLayout_2.addWidget(self.optionsReset_button)
        self.verticalLayout.addWidget(self.widget_4)

        self.retranslateUi(PreferencesDialog)
        self.options_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)
        PreferencesDialog.setTabOrder(self.options_tabs, self.buttonBox)
        PreferencesDialog.setTabOrder(self.buttonBox, self.optionsReset_button)
        PreferencesDialog.setTabOrder(self.optionsReset_button, self.scrollArea)
        PreferencesDialog.setTabOrder(self.scrollArea, self.modeller_name_box)
        PreferencesDialog.setTabOrder(self.modeller_name_box, self.modeller_affil_box)
        PreferencesDialog.setTabOrder(self.modeller_affil_box, self.scrollArea_2)
        PreferencesDialog.setTabOrder(self.scrollArea_2, self.techplan_iter_spin)
        PreferencesDialog.setTabOrder(self.techplan_iter_spin, self.techplan_city_combo)
        PreferencesDialog.setTabOrder(self.techplan_city_combo, self.tech_leaveempty_radio)
        PreferencesDialog.setTabOrder(self.tech_leaveempty_radio, self.tech_highest_radio)
        PreferencesDialog.setTabOrder(self.tech_highest_radio, self.techplan_strats_spin)
        PreferencesDialog.setTabOrder(self.techplan_strats_spin, self.perf_writeMUSICcheck)
        PreferencesDialog.setTabOrder(self.perf_writeMUSICcheck, self.perf_musicauto_check)
        PreferencesDialog.setTabOrder(self.perf_musicauto_check, self.perf_musicpath_box)
        PreferencesDialog.setTabOrder(self.perf_musicpath_box, self.perf_musicpath_browse)
        PreferencesDialog.setTabOrder(self.perf_musicpath_browse, self.perf_musicvercombo)
        PreferencesDialog.setTabOrder(self.perf_musicvercombo, self.perf_tte_check)
        PreferencesDialog.setTabOrder(self.perf_tte_check, self.perf_flux_check)
        PreferencesDialog.setTabOrder(self.perf_flux_check, self.scrollArea_3)
        PreferencesDialog.setTabOrder(self.scrollArea_3, self.style1_radio)
        PreferencesDialog.setTabOrder(self.style1_radio, self.style2_radio)
        PreferencesDialog.setTabOrder(self.style2_radio, self.stylecustom_radio)
        PreferencesDialog.setTabOrder(self.stylecustom_radio, self.results_tileserver_box)
        PreferencesDialog.setTabOrder(self.results_tileserver_box, self.gearth_get)
        PreferencesDialog.setTabOrder(self.gearth_get, self.gearth_path_box)
        PreferencesDialog.setTabOrder(self.gearth_path_box, self.gearth_path_browse)
        PreferencesDialog.setTabOrder(self.gearth_path_browse, self.gearth_auto_check)

    def retranslateUi(self, PreferencesDialog):
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.general_tab), QtGui.QApplication.translate("PreferencesDialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.simulation_tab), QtGui.QApplication.translate("PreferencesDialog", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.options_tabs.setTabText(self.options_tabs.indexOf(self.results_tab), QtGui.QApplication.translate("PreferencesDialog", "Results", None, QtGui.QApplication.UnicodeUTF8))

import guitoolbaricons_rc
import guitoolbaricons_rc
