# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urbanbeatsresultsgui.ui'
#
# Created: Thu Nov 07 16:31:12 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ResultsBrowseDialog(object):
    def setupUi(self, ResultsBrowseDialog):
        ResultsBrowseDialog.setObjectName(_fromUtf8("ResultsBrowseDialog"))
        ResultsBrowseDialog.resize(1024, 681)
        ResultsBrowseDialog.setMinimumSize(QtCore.QSize(1024, 680))
        ResultsBrowseDialog.setWindowTitle(QtGui.QApplication.translate("ResultsBrowseDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(ResultsBrowseDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.title_widget = QtGui.QWidget(ResultsBrowseDialog)
        self.title_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.title_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_widget.setObjectName(_fromUtf8("title_widget"))
        self.line = QtGui.QFrame(self.title_widget)
        self.line.setGeometry(QtCore.QRect(50, 40, 941, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(573, 0))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.windowtitle = QtGui.QLabel(self.title_widget)
        self.windowtitle.setGeometry(QtCore.QRect(50, 5, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.windowtitle.setFont(font)
        self.windowtitle.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Model Output Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.windowtitle.setObjectName(_fromUtf8("windowtitle"))
        self.windowLogo = QtGui.QLabel(self.title_widget)
        self.windowLogo.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.windowLogo.setMaximumSize(QtCore.QSize(50, 50))
        self.windowLogo.setText(_fromUtf8(""))
        self.windowLogo.setPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/outputs.png")))
        self.windowLogo.setObjectName(_fromUtf8("windowLogo"))
        self.windowsubtitle = QtGui.QLabel(self.title_widget)
        self.windowsubtitle.setGeometry(QtCore.QRect(50, 25, 561, 16))
        self.windowsubtitle.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Explore and Export Model Outputs for current Project", None, QtGui.QApplication.UnicodeUTF8))
        self.windowsubtitle.setObjectName(_fromUtf8("windowsubtitle"))
        self.verticalLayout.addWidget(self.title_widget)
        self.main_widget = QtGui.QWidget(ResultsBrowseDialog)
        self.main_widget.setObjectName(_fromUtf8("main_widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.main_widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.resultTabs = QtGui.QTabWidget(self.main_widget)
        self.resultTabs.setEnabled(True)
        self.resultTabs.setObjectName(_fromUtf8("resultTabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ps_sidebarWidget = QtGui.QWidget(self.tab)
        self.ps_sidebarWidget.setMinimumSize(QtCore.QSize(218, 0))
        self.ps_sidebarWidget.setMaximumSize(QtCore.QSize(218, 16777215))
        self.ps_sidebarWidget.setObjectName(_fromUtf8("ps_sidebarWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.ps_sidebarWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ps_categoryTree = QtGui.QTreeWidget(self.ps_sidebarWidget)
        self.ps_categoryTree.setMinimumSize(QtCore.QSize(200, 0))
        self.ps_categoryTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ps_categoryTree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ps_categoryTree.setColumnCount(1)
        self.ps_categoryTree.setObjectName(_fromUtf8("ps_categoryTree"))
        self.ps_categoryTree.headerItem().setText(0, QtGui.QApplication.translate("ResultsBrowseDialog", "Outline", None, QtGui.QApplication.UnicodeUTF8))
        self.ps_categoryTree.header().setVisible(True)
        self.verticalLayout_4.addWidget(self.ps_categoryTree)
        self.ps_exportWidget = QtGui.QWidget(self.ps_sidebarWidget)
        self.ps_exportWidget.setMinimumSize(QtCore.QSize(200, 38))
        self.ps_exportWidget.setMaximumSize(QtCore.QSize(200, 38))
        self.ps_exportWidget.setObjectName(_fromUtf8("ps_exportWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.ps_exportWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ps_exportResults = QtGui.QPushButton(self.ps_exportWidget)
        self.ps_exportResults.setMinimumSize(QtCore.QSize(182, 20))
        self.ps_exportResults.setMaximumSize(QtCore.QSize(182, 20))
        self.ps_exportResults.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Export Summary ...", None, QtGui.QApplication.UnicodeUTF8))
        self.ps_exportResults.setObjectName(_fromUtf8("ps_exportResults"))
        self.verticalLayout_5.addWidget(self.ps_exportResults)
        self.verticalLayout_4.addWidget(self.ps_exportWidget)
        self.horizontalLayout_3.addWidget(self.ps_sidebarWidget)
        self.ps_MainViewWidget = QtGui.QWidget(self.tab)
        self.ps_MainViewWidget.setObjectName(_fromUtf8("ps_MainViewWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.ps_MainViewWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.ps_WebView = QtWebKit.QWebView(self.ps_MainViewWidget)
        self.ps_WebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.ps_WebView.setObjectName(_fromUtf8("ps_WebView"))
        self.verticalLayout_3.addWidget(self.ps_WebView)
        self.horizontalLayout_3.addWidget(self.ps_MainViewWidget)
        self.resultTabs.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.sm_MainViewWidget = QtGui.QWidget(self.tab_5)
        self.sm_MainViewWidget.setObjectName(_fromUtf8("sm_MainViewWidget"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.sm_MainViewWidget)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.sm_WebView = QtWebKit.QWebView(self.sm_MainViewWidget)
        self.sm_WebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.sm_WebView.setObjectName(_fromUtf8("sm_WebView"))
        self.verticalLayout_16.addWidget(self.sm_WebView)
        self.verticalLayout_15.addWidget(self.sm_MainViewWidget)
        self.sm_controlSimWidget = QtGui.QWidget(self.tab_5)
        self.sm_controlSimWidget.setMinimumSize(QtCore.QSize(0, 38))
        self.sm_controlSimWidget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.sm_controlSimWidget.setObjectName(_fromUtf8("sm_controlSimWidget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.sm_controlSimWidget)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.sm_Sim_lbl = QtGui.QLabel(self.sm_controlSimWidget)
        self.sm_Sim_lbl.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Simulation #", None, QtGui.QApplication.UnicodeUTF8))
        self.sm_Sim_lbl.setObjectName(_fromUtf8("sm_Sim_lbl"))
        self.horizontalLayout_10.addWidget(self.sm_Sim_lbl)
        self.sm_ScrollBar = QtGui.QScrollBar(self.sm_controlSimWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sm_ScrollBar.sizePolicy().hasHeightForWidth())
        self.sm_ScrollBar.setSizePolicy(sizePolicy)
        self.sm_ScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        self.sm_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sm_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.sm_ScrollBar.setObjectName(_fromUtf8("sm_ScrollBar"))
        self.horizontalLayout_10.addWidget(self.sm_ScrollBar)
        self.sm_Sim_box = QtGui.QLineEdit(self.sm_controlSimWidget)
        self.sm_Sim_box.setMinimumSize(QtCore.QSize(60, 0))
        self.sm_Sim_box.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sm_Sim_box.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Milestone1", None, QtGui.QApplication.UnicodeUTF8))
        self.sm_Sim_box.setObjectName(_fromUtf8("sm_Sim_box"))
        self.horizontalLayout_10.addWidget(self.sm_Sim_box)
        self.verticalLayout_15.addWidget(self.sm_controlSimWidget)
        self.resultTabs.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ue_sidebarWidget = QtGui.QWidget(self.tab_2)
        self.ue_sidebarWidget.setObjectName(_fromUtf8("ue_sidebarWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.ue_sidebarWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ue_comboSelect = QtGui.QComboBox(self.ue_sidebarWidget)
        self.ue_comboSelect.setMinimumSize(QtCore.QSize(200, 20))
        self.ue_comboSelect.setMaximumSize(QtCore.QSize(200, 20))
        self.ue_comboSelect.setObjectName(_fromUtf8("ue_comboSelect"))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(0, QtGui.QApplication.translate("ResultsBrowseDialog", "<select category>", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(1, QtGui.QApplication.translate("ResultsBrowseDialog", "Allotments and Estates", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(2, QtGui.QApplication.translate("ResultsBrowseDialog", "Available Space Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(3, QtGui.QApplication.translate("ResultsBrowseDialog", "Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(4, QtGui.QApplication.translate("ResultsBrowseDialog", "Impervious Areas", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(5, QtGui.QApplication.translate("ResultsBrowseDialog", "Land Surface Cover Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(6, QtGui.QApplication.translate("ResultsBrowseDialog", "Land Use Mix", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(7, QtGui.QApplication.translate("ResultsBrowseDialog", "Population and Employment", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(8, QtGui.QApplication.translate("ResultsBrowseDialog", "Spatial Metrics", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_comboSelect.addItem(_fromUtf8(""))
        self.ue_comboSelect.setItemText(9, QtGui.QApplication.translate("ResultsBrowseDialog", "Undeveloped Land Type", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_7.addWidget(self.ue_comboSelect)
        self.ue_categoryTree = QtGui.QTreeWidget(self.ue_sidebarWidget)
        self.ue_categoryTree.setMinimumSize(QtCore.QSize(200, 0))
        self.ue_categoryTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ue_categoryTree.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.ue_categoryTree.setObjectName(_fromUtf8("ue_categoryTree"))
        self.ue_categoryTree.headerItem().setText(0, QtGui.QApplication.translate("ResultsBrowseDialog", "Urban Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_7.addWidget(self.ue_categoryTree)
        self.ue_multiselect = QtGui.QRadioButton(self.ue_sidebarWidget)
        self.ue_multiselect.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Enable Multiple Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_multiselect.setObjectName(_fromUtf8("ue_multiselect"))
        self.verticalLayout_7.addWidget(self.ue_multiselect)
        self.ue_neighbourhood = QtGui.QRadioButton(self.ue_sidebarWidget)
        self.ue_neighbourhood.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Show only Block Neighbourhood", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_neighbourhood.setObjectName(_fromUtf8("ue_neighbourhood"))
        self.verticalLayout_7.addWidget(self.ue_neighbourhood)
        self.ue_exportWidget = QtGui.QWidget(self.ue_sidebarWidget)
        self.ue_exportWidget.setMinimumSize(QtCore.QSize(200, 38))
        self.ue_exportWidget.setMaximumSize(QtCore.QSize(200, 38))
        self.ue_exportWidget.setObjectName(_fromUtf8("ue_exportWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.ue_exportWidget)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ue_exportResults = QtGui.QPushButton(self.ue_exportWidget)
        self.ue_exportResults.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Export Results ...", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_exportResults.setObjectName(_fromUtf8("ue_exportResults"))
        self.verticalLayout_8.addWidget(self.ue_exportResults)
        self.verticalLayout_7.addWidget(self.ue_exportWidget)
        self.horizontalLayout_5.addWidget(self.ue_sidebarWidget)
        self.ue_MainViewWidget = QtGui.QWidget(self.tab_2)
        self.ue_MainViewWidget.setObjectName(_fromUtf8("ue_MainViewWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.ue_MainViewWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.ue_WebView = QtWebKit.QWebView(self.ue_MainViewWidget)
        self.ue_WebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.ue_WebView.setObjectName(_fromUtf8("ue_WebView"))
        self.verticalLayout_6.addWidget(self.ue_WebView)
        self.ue_controlSimWidget = QtGui.QWidget(self.ue_MainViewWidget)
        self.ue_controlSimWidget.setObjectName(_fromUtf8("ue_controlSimWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.ue_controlSimWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ue_Sim_lbl = QtGui.QLabel(self.ue_controlSimWidget)
        self.ue_Sim_lbl.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Simulation #", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_Sim_lbl.setObjectName(_fromUtf8("ue_Sim_lbl"))
        self.horizontalLayout_4.addWidget(self.ue_Sim_lbl)
        self.ue_ScrollBar = QtGui.QScrollBar(self.ue_controlSimWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ue_ScrollBar.sizePolicy().hasHeightForWidth())
        self.ue_ScrollBar.setSizePolicy(sizePolicy)
        self.ue_ScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        self.ue_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ue_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.ue_ScrollBar.setObjectName(_fromUtf8("ue_ScrollBar"))
        self.horizontalLayout_4.addWidget(self.ue_ScrollBar)
        self.ue_Sim_box = QtGui.QLineEdit(self.ue_controlSimWidget)
        self.ue_Sim_box.setMinimumSize(QtCore.QSize(60, 0))
        self.ue_Sim_box.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ue_Sim_box.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Milestone1", None, QtGui.QApplication.UnicodeUTF8))
        self.ue_Sim_box.setObjectName(_fromUtf8("ue_Sim_box"))
        self.horizontalLayout_4.addWidget(self.ue_Sim_box)
        self.verticalLayout_6.addWidget(self.ue_controlSimWidget)
        self.horizontalLayout_5.addWidget(self.ue_MainViewWidget)
        self.resultTabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.wi_sidebarWidget = QtGui.QWidget(self.tab_3)
        self.wi_sidebarWidget.setObjectName(_fromUtf8("wi_sidebarWidget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.wi_sidebarWidget)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.wi_comboSelect = QtGui.QComboBox(self.wi_sidebarWidget)
        self.wi_comboSelect.setEnabled(False)
        self.wi_comboSelect.setMinimumSize(QtCore.QSize(200, 20))
        self.wi_comboSelect.setMaximumSize(QtCore.QSize(200, 20))
        self.wi_comboSelect.setObjectName(_fromUtf8("wi_comboSelect"))
        self.wi_comboSelect.addItem(_fromUtf8(""))
        self.wi_comboSelect.setItemText(0, QtGui.QApplication.translate("ResultsBrowseDialog", "<select category>", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_comboSelect.addItem(_fromUtf8(""))
        self.wi_comboSelect.setItemText(1, QtGui.QApplication.translate("ResultsBrowseDialog", "Service Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_comboSelect.addItem(_fromUtf8(""))
        self.wi_comboSelect.setItemText(2, QtGui.QApplication.translate("ResultsBrowseDialog", "Technology Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_comboSelect.addItem(_fromUtf8(""))
        self.wi_comboSelect.setItemText(3, QtGui.QApplication.translate("ResultsBrowseDialog", "Utilisation", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_comboSelect.addItem(_fromUtf8(""))
        self.wi_comboSelect.setItemText(4, QtGui.QApplication.translate("ResultsBrowseDialog", "Water Demands", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_comboSelect.addItem(_fromUtf8(""))
        self.wi_comboSelect.setItemText(5, QtGui.QApplication.translate("ResultsBrowseDialog", "Water Efficiency Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_10.addWidget(self.wi_comboSelect)
        self.wi_categoryTree = QtGui.QTreeWidget(self.wi_sidebarWidget)
        self.wi_categoryTree.setEnabled(False)
        self.wi_categoryTree.setMinimumSize(QtCore.QSize(200, 0))
        self.wi_categoryTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.wi_categoryTree.setObjectName(_fromUtf8("wi_categoryTree"))
        self.wi_categoryTree.headerItem().setText(0, QtGui.QApplication.translate("ResultsBrowseDialog", "Urban Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_10.addWidget(self.wi_categoryTree)
        self.wi_multiselect = QtGui.QRadioButton(self.wi_sidebarWidget)
        self.wi_multiselect.setEnabled(False)
        self.wi_multiselect.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Enable Multiple Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_multiselect.setObjectName(_fromUtf8("wi_multiselect"))
        self.verticalLayout_10.addWidget(self.wi_multiselect)
        self.wi_neighbourhood = QtGui.QRadioButton(self.wi_sidebarWidget)
        self.wi_neighbourhood.setEnabled(False)
        self.wi_neighbourhood.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Show only Block Neighbourhood", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_neighbourhood.setObjectName(_fromUtf8("wi_neighbourhood"))
        self.verticalLayout_10.addWidget(self.wi_neighbourhood)
        self.wi_exportWidget = QtGui.QWidget(self.wi_sidebarWidget)
        self.wi_exportWidget.setMinimumSize(QtCore.QSize(200, 38))
        self.wi_exportWidget.setMaximumSize(QtCore.QSize(200, 38))
        self.wi_exportWidget.setObjectName(_fromUtf8("wi_exportWidget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.wi_exportWidget)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.wi_exportResults = QtGui.QPushButton(self.wi_exportWidget)
        self.wi_exportResults.setEnabled(False)
        self.wi_exportResults.setMinimumSize(QtCore.QSize(0, 0))
        self.wi_exportResults.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wi_exportResults.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Export Results ...", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_exportResults.setObjectName(_fromUtf8("wi_exportResults"))
        self.verticalLayout_11.addWidget(self.wi_exportResults)
        self.verticalLayout_10.addWidget(self.wi_exportWidget)
        self.horizontalLayout_7.addWidget(self.wi_sidebarWidget)
        self.wi_MainViewWidget = QtGui.QWidget(self.tab_3)
        self.wi_MainViewWidget.setObjectName(_fromUtf8("wi_MainViewWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.wi_MainViewWidget)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.wi_WebView = QtWebKit.QWebView(self.wi_MainViewWidget)
        self.wi_WebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.wi_WebView.setObjectName(_fromUtf8("wi_WebView"))
        self.verticalLayout_9.addWidget(self.wi_WebView)
        self.wi_controlSimWidget = QtGui.QWidget(self.wi_MainViewWidget)
        self.wi_controlSimWidget.setObjectName(_fromUtf8("wi_controlSimWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.wi_controlSimWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.wi_Sim_lbl = QtGui.QLabel(self.wi_controlSimWidget)
        self.wi_Sim_lbl.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Simulation #", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_Sim_lbl.setObjectName(_fromUtf8("wi_Sim_lbl"))
        self.horizontalLayout_6.addWidget(self.wi_Sim_lbl)
        self.wi_ScrollBar = QtGui.QScrollBar(self.wi_controlSimWidget)
        self.wi_ScrollBar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wi_ScrollBar.sizePolicy().hasHeightForWidth())
        self.wi_ScrollBar.setSizePolicy(sizePolicy)
        self.wi_ScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        self.wi_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wi_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.wi_ScrollBar.setObjectName(_fromUtf8("wi_ScrollBar"))
        self.horizontalLayout_6.addWidget(self.wi_ScrollBar)
        self.wi_Sim_box = QtGui.QLineEdit(self.wi_controlSimWidget)
        self.wi_Sim_box.setEnabled(False)
        self.wi_Sim_box.setMinimumSize(QtCore.QSize(60, 0))
        self.wi_Sim_box.setMaximumSize(QtCore.QSize(60, 16777215))
        self.wi_Sim_box.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Milestone1", None, QtGui.QApplication.UnicodeUTF8))
        self.wi_Sim_box.setObjectName(_fromUtf8("wi_Sim_box"))
        self.horizontalLayout_6.addWidget(self.wi_Sim_box)
        self.verticalLayout_9.addWidget(self.wi_controlSimWidget)
        self.horizontalLayout_7.addWidget(self.wi_MainViewWidget)
        self.resultTabs.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.sp_sidebarWidget = QtGui.QWidget(self.tab_4)
        self.sp_sidebarWidget.setObjectName(_fromUtf8("sp_sidebarWidget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.sp_sidebarWidget)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.sp_categoryTree = QtGui.QTreeWidget(self.sp_sidebarWidget)
        self.sp_categoryTree.setEnabled(False)
        self.sp_categoryTree.setMinimumSize(QtCore.QSize(200, 0))
        self.sp_categoryTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sp_categoryTree.setObjectName(_fromUtf8("sp_categoryTree"))
        self.sp_categoryTree.headerItem().setText(0, QtGui.QApplication.translate("ResultsBrowseDialog", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_13.addWidget(self.sp_categoryTree)
        self.sp_exportWidget = QtGui.QWidget(self.sp_sidebarWidget)
        self.sp_exportWidget.setMinimumSize(QtCore.QSize(200, 38))
        self.sp_exportWidget.setMaximumSize(QtCore.QSize(200, 38))
        self.sp_exportWidget.setObjectName(_fromUtf8("sp_exportWidget"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.sp_exportWidget)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.sp_exportResults = QtGui.QPushButton(self.sp_exportWidget)
        self.sp_exportResults.setEnabled(False)
        self.sp_exportResults.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Export Results ...", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_exportResults.setObjectName(_fromUtf8("sp_exportResults"))
        self.verticalLayout_14.addWidget(self.sp_exportResults)
        self.verticalLayout_13.addWidget(self.sp_exportWidget)
        self.horizontalLayout_9.addWidget(self.sp_sidebarWidget)
        self.sp_MainViewWidget = QtGui.QWidget(self.tab_4)
        self.sp_MainViewWidget.setObjectName(_fromUtf8("sp_MainViewWidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.sp_MainViewWidget)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.sp_WebView = QtWebKit.QWebView(self.sp_MainViewWidget)
        self.sp_WebView.setEnabled(False)
        self.sp_WebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.sp_WebView.setObjectName(_fromUtf8("sp_WebView"))
        self.verticalLayout_12.addWidget(self.sp_WebView)
        self.sp_controlSimWidget = QtGui.QWidget(self.sp_MainViewWidget)
        self.sp_controlSimWidget.setObjectName(_fromUtf8("sp_controlSimWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.sp_controlSimWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.sp_Sim_lbl = QtGui.QLabel(self.sp_controlSimWidget)
        self.sp_Sim_lbl.setEnabled(False)
        self.sp_Sim_lbl.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Simulation #", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_Sim_lbl.setObjectName(_fromUtf8("sp_Sim_lbl"))
        self.horizontalLayout_8.addWidget(self.sp_Sim_lbl)
        self.sp_ScrollBar = QtGui.QScrollBar(self.sp_controlSimWidget)
        self.sp_ScrollBar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_ScrollBar.sizePolicy().hasHeightForWidth())
        self.sp_ScrollBar.setSizePolicy(sizePolicy)
        self.sp_ScrollBar.setMinimumSize(QtCore.QSize(0, 0))
        self.sp_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.sp_ScrollBar.setObjectName(_fromUtf8("sp_ScrollBar"))
        self.horizontalLayout_8.addWidget(self.sp_ScrollBar)
        self.sp_Sim_box = QtGui.QLineEdit(self.sp_controlSimWidget)
        self.sp_Sim_box.setEnabled(False)
        self.sp_Sim_box.setMinimumSize(QtCore.QSize(60, 0))
        self.sp_Sim_box.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sp_Sim_box.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Milestone1", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_Sim_box.setObjectName(_fromUtf8("sp_Sim_box"))
        self.horizontalLayout_8.addWidget(self.sp_Sim_box)
        self.verticalLayout_12.addWidget(self.sp_controlSimWidget)
        self.horizontalLayout_9.addWidget(self.sp_MainViewWidget)
        self.resultTabs.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.resultTabs)
        self.verticalLayout.addWidget(self.main_widget)
        self.footer = QtGui.QWidget(ResultsBrowseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer.sizePolicy().hasHeightForWidth())
        self.footer.setSizePolicy(sizePolicy)
        self.footer.setMinimumSize(QtCore.QSize(0, 38))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 38))
        self.footer.setObjectName(_fromUtf8("footer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.footer)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.remarks = QtGui.QLabel(self.footer)
        self.remarks.setMinimumSize(QtCore.QSize(900, 0))
        self.remarks.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic;\">UrbanBEATS v1.0 - (C) 2013 Peter M. Bach </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.remarks.setObjectName(_fromUtf8("remarks"))
        self.horizontalLayout.addWidget(self.remarks)
        self.closeButton = QtGui.QPushButton(self.footer)
        self.closeButton.setMinimumSize(QtCore.QSize(82, 20))
        self.closeButton.setMaximumSize(QtCore.QSize(82, 20))
        self.closeButton.setWhatsThis(_fromUtf8(""))
        self.closeButton.setText(QtGui.QApplication.translate("ResultsBrowseDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(ResultsBrowseDialog)
        self.resultTabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ResultsBrowseDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ResultsBrowseDialog)

    def retranslateUi(self, ResultsBrowseDialog):
        self.resultTabs.setTabText(self.resultTabs.indexOf(self.tab), QtGui.QApplication.translate("ResultsBrowseDialog", "Project Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabs.setTabText(self.resultTabs.indexOf(self.tab_5), QtGui.QApplication.translate("ResultsBrowseDialog", "Spatial Map", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabs.setTabText(self.resultTabs.indexOf(self.tab_2), QtGui.QApplication.translate("ResultsBrowseDialog", "Urban Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabs.setTabText(self.resultTabs.indexOf(self.tab_3), QtGui.QApplication.translate("ResultsBrowseDialog", "Water Infrastructure", None, QtGui.QApplication.UnicodeUTF8))
        self.resultTabs.setTabText(self.resultTabs.indexOf(self.tab_4), QtGui.QApplication.translate("ResultsBrowseDialog", "System Performance", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import guitoolbaricons_rc
import guitoolbaricons_rc
import guitoolbaricons_rc
import guitoolbaricons_rc
