# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urbanbeatsmaingui.ui'
#
# Created: Sun Nov 10 21:37:31 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_urbanbeatsMain(object):
    def setupUi(self, urbanbeatsMain):
        urbanbeatsMain.setObjectName(_fromUtf8("urbanbeatsMain"))
        urbanbeatsMain.resize(1280, 700)
        urbanbeatsMain.setMinimumSize(QtCore.QSize(1280, 700))
        urbanbeatsMain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        urbanbeatsMain.setWindowTitle(QtGui.QApplication.translate("urbanbeatsMain", "UrbanBEATS v 1.0 - 2012", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../ubeatslogo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        urbanbeatsMain.setWindowIcon(icon)
        urbanbeatsMain.setWindowOpacity(2.0)
        urbanbeatsMain.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(urbanbeatsMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.simulationWidget = QtGui.QWidget(self.centralwidget)
        self.simulationWidget.setObjectName(_fromUtf8("simulationWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.simulationWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.simconfig_lbl = QtGui.QLabel(self.simulationWidget)
        self.simconfig_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Simulation Configuration</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.simconfig_lbl.setObjectName(_fromUtf8("simconfig_lbl"))
        self.verticalLayout_3.addWidget(self.simconfig_lbl)
        self.widget_2 = QtGui.QWidget(self.simulationWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 390))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.simconfig_tabs = QtGui.QTabWidget(self.widget_2)
        self.simconfig_tabs.setMinimumSize(QtCore.QSize(0, 0))
        self.simconfig_tabs.setObjectName(_fromUtf8("simconfig_tabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.summaryBox0 = QtWebKit.QWebView(self.tab)
        self.summaryBox0.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.summaryBox0.setObjectName(_fromUtf8("summaryBox0"))
        self.verticalLayout_6.addWidget(self.summaryBox0)
        self.revise_check = QtGui.QCheckBox(self.tab)
        self.revise_check.setEnabled(False)
        self.revise_check.setText(QtGui.QApplication.translate("urbanbeatsMain", "Do not Revise Water Management Plan for this instance", None, QtGui.QApplication.UnicodeUTF8))
        self.revise_check.setObjectName(_fromUtf8("revise_check"))
        self.verticalLayout_6.addWidget(self.revise_check)
        self.simconfig_tabs.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.simconfig_tabs)
        self.simcontrol_widget = QtGui.QWidget(self.widget_2)
        self.simcontrol_widget.setMinimumSize(QtCore.QSize(420, 0))
        self.simcontrol_widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.simcontrol_widget.setObjectName(_fromUtf8("simcontrol_widget"))
        self.pc_delinblocks = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_delinblocks.setGeometry(QtCore.QRect(201, 60, 161, 23))
        self.pc_delinblocks.setText(QtGui.QApplication.translate("urbanbeatsMain", "Spatial Delineation", None, QtGui.QApplication.UnicodeUTF8))
        self.pc_delinblocks.setObjectName(_fromUtf8("pc_delinblocks"))
        self.pc_urbplanbb = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_urbplanbb.setGeometry(QtCore.QRect(201, 90, 161, 23))
        self.pc_urbplanbb.setText(QtGui.QApplication.translate("urbanbeatsMain", "Urban Planning Rules", None, QtGui.QApplication.UnicodeUTF8))
        self.pc_urbplanbb.setObjectName(_fromUtf8("pc_urbplanbb"))
        self.pc_techplacement = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_techplacement.setGeometry(QtCore.QRect(201, 120, 161, 23))
        self.pc_techplacement.setText(QtGui.QApplication.translate("urbanbeatsMain", "Technology Customization", None, QtGui.QApplication.UnicodeUTF8))
        self.pc_techplacement.setObjectName(_fromUtf8("pc_techplacement"))
        self.ic_techimplement = QtGui.QPushButton(self.simcontrol_widget)
        self.ic_techimplement.setGeometry(QtCore.QRect(200, 180, 161, 23))
        self.ic_techimplement.setText(QtGui.QApplication.translate("urbanbeatsMain", "Technology Implementation", None, QtGui.QApplication.UnicodeUTF8))
        self.ic_techimplement.setObjectName(_fromUtf8("ic_techimplement"))
        self.pc_dataset = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_dataset.setGeometry(QtCore.QRect(131, 50, 61, 61))
        self.pc_dataset.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/Layers-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pc_dataset.setIcon(icon1)
        self.pc_dataset.setIconSize(QtCore.QSize(48, 48))
        self.pc_dataset.setObjectName(_fromUtf8("pc_dataset"))
        self.pa_assesspc = QtGui.QPushButton(self.simcontrol_widget)
        self.pa_assesspc.setGeometry(QtCore.QRect(200, 290, 161, 23))
        self.pa_assesspc.setText(QtGui.QApplication.translate("urbanbeatsMain", "Assess for Planning Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.pa_assesspc.setObjectName(_fromUtf8("pa_assesspc"))
        self.pc_lbl = QtGui.QLabel(self.simcontrol_widget)
        self.pc_lbl.setGeometry(QtCore.QRect(10, 25, 91, 20))
        self.pc_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Planning Cycle</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pc_lbl.setObjectName(_fromUtf8("pc_lbl"))
        self.ic_lbl = QtGui.QLabel(self.simcontrol_widget)
        self.ic_lbl.setGeometry(QtCore.QRect(10, 155, 351, 20))
        self.ic_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Implementation Cycle</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ic_lbl.setObjectName(_fromUtf8("ic_lbl"))
        self.pa_lbl = QtGui.QLabel(self.simcontrol_widget)
        self.pa_lbl.setGeometry(QtCore.QRect(10, 265, 351, 20))
        self.pa_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Performance Assessment</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pa_lbl.setObjectName(_fromUtf8("pa_lbl"))
        self.pa_skippc = QtGui.QCheckBox(self.simcontrol_widget)
        self.pa_skippc.setGeometry(QtCore.QRect(205, 350, 261, 17))
        self.pa_skippc.setText(QtGui.QApplication.translate("urbanbeatsMain", "Skip Planning Cycle Assessment", None, QtGui.QApplication.UnicodeUTF8))
        self.pa_skippc.setObjectName(_fromUtf8("pa_skippc"))
        self.ic_dataset = QtGui.QPushButton(self.simcontrol_widget)
        self.ic_dataset.setGeometry(QtCore.QRect(130, 180, 61, 61))
        self.ic_dataset.setText(_fromUtf8(""))
        self.ic_dataset.setIcon(icon1)
        self.ic_dataset.setIconSize(QtCore.QSize(48, 48))
        self.ic_dataset.setObjectName(_fromUtf8("ic_dataset"))
        self.pa_assessic = QtGui.QPushButton(self.simcontrol_widget)
        self.pa_assessic.setGeometry(QtCore.QRect(200, 320, 161, 23))
        self.pa_assessic.setText(QtGui.QApplication.translate("urbanbeatsMain", "Assess after Implementation", None, QtGui.QApplication.UnicodeUTF8))
        self.pa_assessic.setObjectName(_fromUtf8("pa_assessic"))
        self.pa_dataset = QtGui.QPushButton(self.simcontrol_widget)
        self.pa_dataset.setGeometry(QtCore.QRect(130, 290, 61, 61))
        self.pa_dataset.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/climatedata.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pa_dataset.setIcon(icon2)
        self.pa_dataset.setIconSize(QtCore.QSize(48, 48))
        self.pa_dataset.setObjectName(_fromUtf8("pa_dataset"))
        self.pc_delinblocks_help = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_delinblocks_help.setGeometry(QtCore.QRect(381, 60, 23, 23))
        self.pc_delinblocks_help.setMinimumSize(QtCore.QSize(23, 23))
        self.pc_delinblocks_help.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pc_delinblocks_help.setIcon(icon3)
        self.pc_delinblocks_help.setIconSize(QtCore.QSize(23, 23))
        self.pc_delinblocks_help.setObjectName(_fromUtf8("pc_delinblocks_help"))
        self.pc_urbplanbb_help = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_urbplanbb_help.setGeometry(QtCore.QRect(381, 90, 23, 23))
        self.pc_urbplanbb_help.setMinimumSize(QtCore.QSize(23, 23))
        self.pc_urbplanbb_help.setText(_fromUtf8(""))
        self.pc_urbplanbb_help.setIcon(icon3)
        self.pc_urbplanbb_help.setIconSize(QtCore.QSize(23, 23))
        self.pc_urbplanbb_help.setObjectName(_fromUtf8("pc_urbplanbb_help"))
        self.pc_techplacement_help = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_techplacement_help.setGeometry(QtCore.QRect(381, 120, 23, 23))
        self.pc_techplacement_help.setMinimumSize(QtCore.QSize(23, 23))
        self.pc_techplacement_help.setText(_fromUtf8(""))
        self.pc_techplacement_help.setIcon(icon3)
        self.pc_techplacement_help.setIconSize(QtCore.QSize(23, 23))
        self.pc_techplacement_help.setObjectName(_fromUtf8("pc_techplacement_help"))
        self.ic_techimplement_help = QtGui.QPushButton(self.simcontrol_widget)
        self.ic_techimplement_help.setGeometry(QtCore.QRect(380, 180, 23, 23))
        self.ic_techimplement_help.setMinimumSize(QtCore.QSize(23, 23))
        self.ic_techimplement_help.setText(_fromUtf8(""))
        self.ic_techimplement_help.setIcon(icon3)
        self.ic_techimplement_help.setIconSize(QtCore.QSize(23, 23))
        self.ic_techimplement_help.setObjectName(_fromUtf8("ic_techimplement_help"))
        self.pa_assesspc_help = QtGui.QPushButton(self.simcontrol_widget)
        self.pa_assesspc_help.setGeometry(QtCore.QRect(380, 290, 23, 23))
        self.pa_assesspc_help.setMinimumSize(QtCore.QSize(23, 23))
        self.pa_assesspc_help.setText(_fromUtf8(""))
        self.pa_assesspc_help.setIcon(icon3)
        self.pa_assesspc_help.setIconSize(QtCore.QSize(23, 23))
        self.pa_assesspc_help.setObjectName(_fromUtf8("pa_assesspc_help"))
        self.pa_assessic_help = QtGui.QPushButton(self.simcontrol_widget)
        self.pa_assessic_help.setGeometry(QtCore.QRect(380, 320, 23, 23))
        self.pa_assessic_help.setMinimumSize(QtCore.QSize(23, 23))
        self.pa_assessic_help.setText(_fromUtf8(""))
        self.pa_assessic_help.setIcon(icon3)
        self.pa_assessic_help.setIconSize(QtCore.QSize(23, 23))
        self.pa_assessic_help.setObjectName(_fromUtf8("pa_assessic_help"))
        self.label = QtGui.QLabel(self.simcontrol_widget)
        self.label.setGeometry(QtCore.QRect(140, 110, 46, 13))
        self.label.setText(QtGui.QApplication.translate("urbanbeatsMain", "Set Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.simcontrol_widget)
        self.label_2.setGeometry(QtCore.QRect(140, 240, 46, 13))
        self.label_2.setText(QtGui.QApplication.translate("urbanbeatsMain", "Set Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.simcontrol_widget)
        self.label_3.setGeometry(QtCore.QRect(140, 350, 46, 13))
        self.label_3.setText(QtGui.QApplication.translate("urbanbeatsMain", "Set Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pa_img = QtGui.QLabel(self.simcontrol_widget)
        self.pa_img.setGeometry(QtCore.QRect(20, 290, 81, 81))
        self.pa_img.setText(_fromUtf8(""))
        self.pa_img.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/cycle_perf_icon.png")))
        self.pa_img.setObjectName(_fromUtf8("pa_img"))
        self.ic_img = QtGui.QLabel(self.simcontrol_widget)
        self.ic_img.setGeometry(QtCore.QRect(20, 175, 81, 81))
        self.ic_img.setText(_fromUtf8(""))
        self.ic_img.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/cycle_implement_icon.png")))
        self.ic_img.setObjectName(_fromUtf8("ic_img"))
        self.pc_img = QtGui.QLabel(self.simcontrol_widget)
        self.pc_img.setGeometry(QtCore.QRect(20, 50, 81, 81))
        self.pc_img.setText(_fromUtf8(""))
        self.pc_img.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/cycle_planning_icon.png")))
        self.pc_img.setObjectName(_fromUtf8("pc_img"))
        self.pcic_divider = QtGui.QFrame(self.simcontrol_widget)
        self.pcic_divider.setGeometry(QtCore.QRect(10, 145, 411, 20))
        self.pcic_divider.setFrameShape(QtGui.QFrame.HLine)
        self.pcic_divider.setFrameShadow(QtGui.QFrame.Sunken)
        self.pcic_divider.setObjectName(_fromUtf8("pcic_divider"))
        self.icpa_divider = QtGui.QFrame(self.simcontrol_widget)
        self.icpa_divider.setGeometry(QtCore.QRect(10, 255, 411, 20))
        self.icpa_divider.setFrameShape(QtGui.QFrame.HLine)
        self.icpa_divider.setFrameShadow(QtGui.QFrame.Sunken)
        self.icpa_divider.setObjectName(_fromUtf8("icpa_divider"))
        self.pc_lbl_2 = QtGui.QLabel(self.simcontrol_widget)
        self.pc_lbl_2.setGeometry(QtCore.QRect(10, 0, 271, 20))
        self.pc_lbl_2.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Model Setup Options for Current Tab</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pc_lbl_2.setObjectName(_fromUtf8("pc_lbl_2"))
        self.pc_narrative = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_narrative.setGeometry(QtCore.QRect(200, 30, 161, 23))
        self.pc_narrative.setText(QtGui.QApplication.translate("urbanbeatsMain", "Narrative Description", None, QtGui.QApplication.UnicodeUTF8))
        self.pc_narrative.setObjectName(_fromUtf8("pc_narrative"))
        self.pc_delinblocks_help_2 = QtGui.QPushButton(self.simcontrol_widget)
        self.pc_delinblocks_help_2.setGeometry(QtCore.QRect(380, 30, 23, 23))
        self.pc_delinblocks_help_2.setMinimumSize(QtCore.QSize(23, 23))
        self.pc_delinblocks_help_2.setText(_fromUtf8(""))
        self.pc_delinblocks_help_2.setIcon(icon3)
        self.pc_delinblocks_help_2.setIconSize(QtCore.QSize(23, 23))
        self.pc_delinblocks_help_2.setObjectName(_fromUtf8("pc_delinblocks_help_2"))
        self.horizontalLayout_6.addWidget(self.simcontrol_widget)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.outputconfig_lbl = QtGui.QLabel(self.simulationWidget)
        self.outputconfig_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Outputs &amp; Reporting Options</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.outputconfig_lbl.setObjectName(_fromUtf8("outputconfig_lbl"))
        self.verticalLayout_3.addWidget(self.outputconfig_lbl)
        self.outputconfig_widget = QtGui.QWidget(self.simulationWidget)
        self.outputconfig_widget.setMinimumSize(QtCore.QSize(0, 120))
        self.outputconfig_widget.setMaximumSize(QtCore.QSize(16777215, 160))
        self.outputconfig_widget.setObjectName(_fromUtf8("outputconfig_widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.outputconfig_widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ubeatsConsole = QtGui.QPlainTextEdit(self.outputconfig_widget)
        self.ubeatsConsole.setReadOnly(False)
        self.ubeatsConsole.setObjectName(_fromUtf8("ubeatsConsole"))
        self.horizontalLayout_3.addWidget(self.ubeatsConsole)
        self.widget = QtGui.QWidget(self.outputconfig_widget)
        self.widget.setMinimumSize(QtCore.QSize(420, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.out_gis_lbl = QtGui.QLabel(self.widget)
        self.out_gis_lbl.setGeometry(QtCore.QRect(26, 45, 91, 20))
        self.out_gis_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Map Export</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.out_gis_lbl.setObjectName(_fromUtf8("out_gis_lbl"))
        self.out_resultsbrowse = QtGui.QPushButton(self.widget)
        self.out_resultsbrowse.setEnabled(False)
        self.out_resultsbrowse.setGeometry(QtCore.QRect(263, 15, 61, 61))
        self.out_resultsbrowse.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/outputs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.out_resultsbrowse.setIcon(icon4)
        self.out_resultsbrowse.setIconSize(QtCore.QSize(48, 48))
        self.out_resultsbrowse.setObjectName(_fromUtf8("out_resultsbrowse"))
        self.out_advanced_lbl = QtGui.QLabel(self.widget)
        self.out_advanced_lbl.setGeometry(QtCore.QRect(265, 75, 61, 20))
        self.out_advanced_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "View Results", None, QtGui.QApplication.UnicodeUTF8))
        self.out_advanced_lbl.setObjectName(_fromUtf8("out_advanced_lbl"))
        self.out_gis_maps = QtGui.QPushButton(self.widget)
        self.out_gis_maps.setGeometry(QtCore.QRect(120, 45, 121, 23))
        self.out_gis_maps.setText(QtGui.QApplication.translate("urbanbeatsMain", "Select Maps", None, QtGui.QApplication.UnicodeUTF8))
        self.out_gis_maps.setObjectName(_fromUtf8("out_gis_maps"))
        self.out_gis_customize = QtGui.QPushButton(self.widget)
        self.out_gis_customize.setGeometry(QtCore.QRect(120, 75, 121, 23))
        self.out_gis_customize.setText(QtGui.QApplication.translate("urbanbeatsMain", "Customize GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.out_gis_customize.setObjectName(_fromUtf8("out_gis_customize"))
        self.out_textrep_lbl = QtGui.QLabel(self.widget)
        self.out_textrep_lbl.setGeometry(QtCore.QRect(26, 15, 121, 20))
        self.out_textrep_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Text Report</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.out_textrep_lbl.setObjectName(_fromUtf8("out_textrep_lbl"))
        self.out_textrep_select = QtGui.QPushButton(self.widget)
        self.out_textrep_select.setGeometry(QtCore.QRect(120, 15, 121, 23))
        self.out_textrep_select.setText(QtGui.QApplication.translate("urbanbeatsMain", "Select Headings", None, QtGui.QApplication.UnicodeUTF8))
        self.out_textrep_select.setObjectName(_fromUtf8("out_textrep_select"))
        self.out_projectfolder_lbl = QtGui.QLabel(self.widget)
        self.out_projectfolder_lbl.setGeometry(QtCore.QRect(340, 75, 71, 20))
        self.out_projectfolder_lbl.setText(QtGui.QApplication.translate("urbanbeatsMain", "Project Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.out_projectfolder_lbl.setObjectName(_fromUtf8("out_projectfolder_lbl"))
        self.out_projectfolder = QtGui.QPushButton(self.widget)
        self.out_projectfolder.setEnabled(False)
        self.out_projectfolder.setGeometry(QtCore.QRect(341, 15, 61, 61))
        self.out_projectfolder.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/folder-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.out_projectfolder.setIcon(icon5)
        self.out_projectfolder.setIconSize(QtCore.QSize(48, 48))
        self.out_projectfolder.setObjectName(_fromUtf8("out_projectfolder"))
        self.icpa_divider_2 = QtGui.QFrame(self.widget)
        self.icpa_divider_2.setGeometry(QtCore.QRect(5, -4, 411, 20))
        self.icpa_divider_2.setFrameShape(QtGui.QFrame.HLine)
        self.icpa_divider_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.icpa_divider_2.setObjectName(_fromUtf8("icpa_divider_2"))
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.outputconfig_widget)
        self.verticalLayout.addWidget(self.simulationWidget)
        self.progressbarWidget = QtGui.QWidget(self.centralwidget)
        self.progressbarWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.progressbarWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.progressbarWidget.setObjectName(_fromUtf8("progressbarWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.progressbarWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.progressBar = QtGui.QProgressBar(self.progressbarWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.progressbarWidget)
        urbanbeatsMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(urbanbeatsMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuAdd_GIS_Data = QtGui.QMenu(self.menuData)
        self.menuAdd_GIS_Data.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Add GIS Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_GIS_Data.setObjectName(_fromUtf8("menuAdd_GIS_Data"))
        self.menuAdd_Climate_Data = QtGui.QMenu(self.menuData)
        self.menuAdd_Climate_Data.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Add Climate Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_Climate_Data.setObjectName(_fromUtf8("menuAdd_Climate_Data"))
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setObjectName(_fromUtf8("menuSimulation"))
        self.menuSetup_Performance_Assessment = QtGui.QMenu(self.menuSimulation)
        self.menuSetup_Performance_Assessment.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Setup Performance Assessment", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSetup_Performance_Assessment.setObjectName(_fromUtf8("menuSetup_Performance_Assessment"))
        self.menuAdvanced = QtGui.QMenu(self.menubar)
        self.menuAdvanced.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdvanced.setObjectName(_fromUtf8("menuAdvanced"))
        self.menuUrban_Form = QtGui.QMenu(self.menuAdvanced)
        self.menuUrban_Form.setEnabled(True)
        self.menuUrban_Form.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Urban Form Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUrban_Form.setObjectName(_fromUtf8("menuUrban_Form"))
        self.menuFacilities = QtGui.QMenu(self.menuUrban_Form)
        self.menuFacilities.setEnabled(True)
        self.menuFacilities.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Facilities", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFacilities.setObjectName(_fromUtf8("menuFacilities"))
        self.menuExternal_Programs = QtGui.QMenu(self.menuAdvanced)
        self.menuExternal_Programs.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "External Programs", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExternal_Programs.setObjectName(_fromUtf8("menuExternal_Programs"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("urbanbeatsMain", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        urbanbeatsMain.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(urbanbeatsMain)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("urbanbeatsMain", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        urbanbeatsMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(urbanbeatsMain)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        urbanbeatsMain.setStatusBar(self.statusBar)
        self.ubeatsDock = QtGui.QDockWidget(urbanbeatsMain)
        self.ubeatsDock.setMinimumSize(QtCore.QSize(310, 331))
        self.ubeatsDock.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.ubeatsDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.ubeatsDock.setWindowTitle(_fromUtf8(""))
        self.ubeatsDock.setObjectName(_fromUtf8("ubeatsDock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.databrowserWidget = QtGui.QWidget(self.dockWidgetContents_4)
        self.databrowserWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.databrowserWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.databrowserWidget.setObjectName(_fromUtf8("databrowserWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.databrowserWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.databrowseTree = QtGui.QTreeWidget(self.databrowserWidget)
        self.databrowseTree.setObjectName(_fromUtf8("databrowseTree"))
        self.databrowseTree.headerItem().setText(0, QtGui.QApplication.translate("urbanbeatsMain", "Active Project Input Data Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_4.addWidget(self.databrowseTree)
        self.dataedit_button_box = QtGui.QWidget(self.databrowserWidget)
        self.dataedit_button_box.setMinimumSize(QtCore.QSize(0, 50))
        self.dataedit_button_box.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dataedit_button_box.setObjectName(_fromUtf8("dataedit_button_box"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dataedit_button_box)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.addDataButton = QtGui.QPushButton(self.dataedit_button_box)
        self.addDataButton.setText(QtGui.QApplication.translate("urbanbeatsMain", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.addDataButton.setObjectName(_fromUtf8("addDataButton"))
        self.horizontalLayout_4.addWidget(self.addDataButton)
        self.removeDataButton = QtGui.QPushButton(self.dataedit_button_box)
        self.removeDataButton.setText(QtGui.QApplication.translate("urbanbeatsMain", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.removeDataButton.setObjectName(_fromUtf8("removeDataButton"))
        self.horizontalLayout_4.addWidget(self.removeDataButton)
        self.collex_button = QtGui.QPushButton(self.dataedit_button_box)
        self.collex_button.setMinimumSize(QtCore.QSize(90, 0))
        self.collex_button.setText(QtGui.QApplication.translate("urbanbeatsMain", "Expand All", None, QtGui.QApplication.UnicodeUTF8))
        self.collex_button.setObjectName(_fromUtf8("collex_button"))
        self.horizontalLayout_4.addWidget(self.collex_button)
        self.verticalLayout_4.addWidget(self.dataedit_button_box)
        self.sim_control_widget = QtGui.QWidget(self.databrowserWidget)
        self.sim_control_widget.setMinimumSize(QtCore.QSize(0, 140))
        self.sim_control_widget.setMaximumSize(QtCore.QSize(16777215, 130))
        self.sim_control_widget.setObjectName(_fromUtf8("sim_control_widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.sim_control_widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ubeatslogo = QtGui.QLabel(self.sim_control_widget)
        self.ubeatslogo.setText(_fromUtf8(""))
        self.ubeatslogo.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/ubeatslogo128x128.png")))
        self.ubeatslogo.setObjectName(_fromUtf8("ubeatslogo"))
        self.horizontalLayout_2.addWidget(self.ubeatslogo)
        self.simbutton_widget = QtGui.QWidget(self.sim_control_widget)
        self.simbutton_widget.setObjectName(_fromUtf8("simbutton_widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.simbutton_widget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.resetSimButton = QtGui.QPushButton(self.simbutton_widget)
        self.resetSimButton.setEnabled(True)
        self.resetSimButton.setText(QtGui.QApplication.translate("urbanbeatsMain", "Reset Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.resetSimButton.setObjectName(_fromUtf8("resetSimButton"))
        self.verticalLayout_5.addWidget(self.resetSimButton)
        self.runButton = QtGui.QPushButton(self.simbutton_widget)
        self.runButton.setMinimumSize(QtCore.QSize(86, 60))
        self.runButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/Play-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon6)
        self.runButton.setIconSize(QtCore.QSize(48, 48))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.verticalLayout_5.addWidget(self.runButton)
        self.horizontalLayout_2.addWidget(self.simbutton_widget)
        self.verticalLayout_4.addWidget(self.sim_control_widget)
        self.horizontalLayout_5.addWidget(self.databrowserWidget)
        self.ubeatsDock.setWidget(self.dockWidgetContents_4)
        urbanbeatsMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.ubeatsDock)
        self.actionNew = QtGui.QAction(urbanbeatsMain)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon7)
        self.actionNew.setText(QtGui.QApplication.translate("urbanbeatsMain", "New Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(urbanbeatsMain)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setText(QtGui.QApplication.translate("urbanbeatsMain", "Open Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(urbanbeatsMain)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon8)
        self.actionSave.setText(QtGui.QApplication.translate("urbanbeatsMain", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(urbanbeatsMain)
        self.actionSave_As.setText(QtGui.QApplication.translate("urbanbeatsMain", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionExit = QtGui.QAction(urbanbeatsMain)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon9)
        self.actionExit.setText(QtGui.QApplication.translate("urbanbeatsMain", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSet_Spatial_Delineation = QtGui.QAction(urbanbeatsMain)
        self.actionSet_Spatial_Delineation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Set Spatial Delineation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Spatial_Delineation.setObjectName(_fromUtf8("actionSet_Spatial_Delineation"))
        self.actionDefine_Urban_Planning_Rules = QtGui.QAction(urbanbeatsMain)
        self.actionDefine_Urban_Planning_Rules.setText(QtGui.QApplication.translate("urbanbeatsMain", "Urban Planning Rules...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefine_Urban_Planning_Rules.setObjectName(_fromUtf8("actionDefine_Urban_Planning_Rules"))
        self.actionCustomize_Technologies = QtGui.QAction(urbanbeatsMain)
        self.actionCustomize_Technologies.setText(QtGui.QApplication.translate("urbanbeatsMain", "Customize Technologies...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCustomize_Technologies.setObjectName(_fromUtf8("actionCustomize_Technologies"))
        self.actionTechnology_Implementation = QtGui.QAction(urbanbeatsMain)
        self.actionTechnology_Implementation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Technology Implementation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTechnology_Implementation.setObjectName(_fromUtf8("actionTechnology_Implementation"))
        self.actionAbout = QtGui.QAction(urbanbeatsMain)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon10)
        self.actionAbout.setText(QtGui.QApplication.translate("urbanbeatsMain", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionUrbanBEATS_Wiki = QtGui.QAction(urbanbeatsMain)
        self.actionUrbanBEATS_Wiki.setIcon(icon3)
        self.actionUrbanBEATS_Wiki.setText(QtGui.QApplication.translate("urbanbeatsMain", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUrbanBEATS_Wiki.setObjectName(_fromUtf8("actionUrbanBEATS_Wiki"))
        self.actionLike_on_Facebook = QtGui.QAction(urbanbeatsMain)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/facebook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLike_on_Facebook.setIcon(icon11)
        self.actionLike_on_Facebook.setText(QtGui.QApplication.translate("urbanbeatsMain", "Like on Facebook", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLike_on_Facebook.setObjectName(_fromUtf8("actionLike_on_Facebook"))
        self.action_1_on_Google = QtGui.QAction(urbanbeatsMain)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/googleplus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_1_on_Google.setIcon(icon12)
        self.action_1_on_Google.setText(QtGui.QApplication.translate("urbanbeatsMain", "+1 on Google+", None, QtGui.QApplication.UnicodeUTF8))
        self.action_1_on_Google.setObjectName(_fromUtf8("action_1_on_Google"))
        self.actionElevation_Data = QtGui.QAction(urbanbeatsMain)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/contourelevation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionElevation_Data.setIcon(icon13)
        self.actionElevation_Data.setText(QtGui.QApplication.translate("urbanbeatsMain", "Elevation Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionElevation_Data.setObjectName(_fromUtf8("actionElevation_Data"))
        self.actionSoil_Data = QtGui.QAction(urbanbeatsMain)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/driver-mud.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSoil_Data.setIcon(icon14)
        self.actionSoil_Data.setText(QtGui.QApplication.translate("urbanbeatsMain", "Soil Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSoil_Data.setObjectName(_fromUtf8("actionSoil_Data"))
        self.actionLand_Use = QtGui.QAction(urbanbeatsMain)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLand_Use.setIcon(icon15)
        self.actionLand_Use.setText(QtGui.QApplication.translate("urbanbeatsMain", "Land Use", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLand_Use.setObjectName(_fromUtf8("actionLand_Use"))
        self.actionPopulation = QtGui.QAction(urbanbeatsMain)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/people.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPopulation.setIcon(icon16)
        self.actionPopulation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Population", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPopulation.setObjectName(_fromUtf8("actionPopulation"))
        self.actionPlanning = QtGui.QAction(urbanbeatsMain)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/blueprint tool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlanning.setIcon(icon17)
        self.actionPlanning.setText(QtGui.QApplication.translate("urbanbeatsMain", "Planning", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlanning.setObjectName(_fromUtf8("actionPlanning"))
        self.actionLocality_Map = QtGui.QAction(urbanbeatsMain)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLocality_Map.setIcon(icon18)
        self.actionLocality_Map.setText(QtGui.QApplication.translate("urbanbeatsMain", "Locality Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocality_Map.setObjectName(_fromUtf8("actionLocality_Map"))
        self.actionRainfall = QtGui.QAction(urbanbeatsMain)
        self.actionRainfall.setIcon(icon2)
        self.actionRainfall.setText(QtGui.QApplication.translate("urbanbeatsMain", "Rainfall", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRainfall.setObjectName(_fromUtf8("actionRainfall"))
        self.actionEvapotranspiration = QtGui.QAction(urbanbeatsMain)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/tree.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEvapotranspiration.setIcon(icon19)
        self.actionEvapotranspiration.setText(QtGui.QApplication.translate("urbanbeatsMain", "Evapotranspiration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvapotranspiration.setObjectName(_fromUtf8("actionEvapotranspiration"))
        self.actionSolar_Radiation = QtGui.QAction(urbanbeatsMain)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/thermo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSolar_Radiation.setIcon(icon20)
        self.actionSolar_Radiation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Solar Radiation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSolar_Radiation.setObjectName(_fromUtf8("actionSolar_Radiation"))
        self.actionReset_Project_Databank = QtGui.QAction(urbanbeatsMain)
        self.actionReset_Project_Databank.setText(QtGui.QApplication.translate("urbanbeatsMain", "Reset Project Databank", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Project_Databank.setObjectName(_fromUtf8("actionReset_Project_Databank"))
        self.actionResidential = QtGui.QAction(urbanbeatsMain)
        self.actionResidential.setEnabled(False)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/home-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResidential.setIcon(icon21)
        self.actionResidential.setText(QtGui.QApplication.translate("urbanbeatsMain", "Residential", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResidential.setObjectName(_fromUtf8("actionResidential"))
        self.actionNon_Residential = QtGui.QAction(urbanbeatsMain)
        self.actionNon_Residential.setEnabled(False)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/industry-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNon_Residential.setIcon(icon22)
        self.actionNon_Residential.setText(QtGui.QApplication.translate("urbanbeatsMain", "Non-Residential", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNon_Residential.setObjectName(_fromUtf8("actionNon_Residential"))
        self.actionEducation = QtGui.QAction(urbanbeatsMain)
        self.actionEducation.setEnabled(False)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/library.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEducation.setIcon(icon23)
        self.actionEducation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEducation.setObjectName(_fromUtf8("actionEducation"))
        self.actionCivic = QtGui.QAction(urbanbeatsMain)
        self.actionCivic.setEnabled(False)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/CatholicTemple-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCivic.setIcon(icon24)
        self.actionCivic.setText(QtGui.QApplication.translate("urbanbeatsMain", "Civic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCivic.setObjectName(_fromUtf8("actionCivic"))
        self.actionTransport = QtGui.QAction(urbanbeatsMain)
        self.actionTransport.setEnabled(False)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/AirPort-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTransport.setIcon(icon25)
        self.actionTransport.setText(QtGui.QApplication.translate("urbanbeatsMain", "Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTransport.setObjectName(_fromUtf8("actionTransport"))
        self.actionSimulation_Options = QtGui.QAction(urbanbeatsMain)
        self.actionSimulation_Options.setEnabled(False)
        self.actionSimulation_Options.setIcon(icon17)
        self.actionSimulation_Options.setText(QtGui.QApplication.translate("urbanbeatsMain", "Simulation Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Options.setObjectName(_fromUtf8("actionSimulation_Options"))
        self.actionOutput_Options = QtGui.QAction(urbanbeatsMain)
        self.actionOutput_Options.setEnabled(False)
        self.actionOutput_Options.setIcon(icon4)
        self.actionOutput_Options.setText(QtGui.QApplication.translate("urbanbeatsMain", "Output Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOutput_Options.setObjectName(_fromUtf8("actionOutput_Options"))
        self.actionCross_check_GIS_Extents = QtGui.QAction(urbanbeatsMain)
        self.actionCross_check_GIS_Extents.setIcon(icon1)
        self.actionCross_check_GIS_Extents.setText(QtGui.QApplication.translate("urbanbeatsMain", "Cross-check GIS Extents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCross_check_GIS_Extents.setObjectName(_fromUtf8("actionCross_check_GIS_Extents"))
        self.actionPreferences = QtGui.QAction(urbanbeatsMain)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon26)
        self.actionPreferences.setText(QtGui.QApplication.translate("urbanbeatsMain", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionCut = QtGui.QAction(urbanbeatsMain)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon27)
        self.actionCut.setText(QtGui.QApplication.translate("urbanbeatsMain", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(urbanbeatsMain)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon28)
        self.actionCopy.setText(QtGui.QApplication.translate("urbanbeatsMain", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(urbanbeatsMain)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon29)
        self.actionPaste.setText(QtGui.QApplication.translate("urbanbeatsMain", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionEdit_Project_Info = QtGui.QAction(urbanbeatsMain)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/tablet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Project_Info.setIcon(icon30)
        self.actionEdit_Project_Info.setText(QtGui.QApplication.translate("urbanbeatsMain", "Edit Project Info...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Project_Info.setObjectName(_fromUtf8("actionEdit_Project_Info"))
        self.actionProject_Description = QtGui.QAction(urbanbeatsMain)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/document-library.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProject_Description.setIcon(icon31)
        self.actionProject_Description.setText(QtGui.QApplication.translate("urbanbeatsMain", "Project Description", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProject_Description.setObjectName(_fromUtf8("actionProject_Description"))
        self.actionUndo = QtGui.QAction(urbanbeatsMain)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon32)
        self.actionUndo.setText(QtGui.QApplication.translate("urbanbeatsMain", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(urbanbeatsMain)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon33)
        self.actionRedo.setText(QtGui.QApplication.translate("urbanbeatsMain", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionMinimize = QtGui.QAction(urbanbeatsMain)
        self.actionMinimize.setText(QtGui.QApplication.translate("urbanbeatsMain", "Minimize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimize.setObjectName(_fromUtf8("actionMinimize"))
        self.actionVerify_Simulation_Setup = QtGui.QAction(urbanbeatsMain)
        self.actionVerify_Simulation_Setup.setEnabled(False)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVerify_Simulation_Setup.setIcon(icon34)
        self.actionVerify_Simulation_Setup.setText(QtGui.QApplication.translate("urbanbeatsMain", "Verify Simulation Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerify_Simulation_Setup.setObjectName(_fromUtf8("actionVerify_Simulation_Setup"))
        self.actionRun_Simulation = QtGui.QAction(urbanbeatsMain)
        self.actionRun_Simulation.setIcon(icon6)
        self.actionRun_Simulation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Run Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Simulation.setObjectName(_fromUtf8("actionRun_Simulation"))
        self.actionActiveWindow = QtGui.QAction(urbanbeatsMain)
        self.actionActiveWindow.setText(QtGui.QApplication.translate("urbanbeatsMain", "ActiveWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActiveWindow.setObjectName(_fromUtf8("actionActiveWindow"))
        self.actionTweet_your_activity = QtGui.QAction(urbanbeatsMain)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/twitter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTweet_your_activity.setIcon(icon35)
        self.actionTweet_your_activity.setText(QtGui.QApplication.translate("urbanbeatsMain", "Tweet your activity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTweet_your_activity.setObjectName(_fromUtf8("actionTweet_your_activity"))
        self.actionAddData = QtGui.QAction(urbanbeatsMain)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddData.setIcon(icon36)
        self.actionAddData.setText(QtGui.QApplication.translate("urbanbeatsMain", "Add Data...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddData.setShortcut(QtGui.QApplication.translate("urbanbeatsMain", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddData.setObjectName(_fromUtf8("actionAddData"))
        self.actionSocial_Data = QtGui.QAction(urbanbeatsMain)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/bubble.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSocial_Data.setIcon(icon37)
        self.actionSocial_Data.setText(QtGui.QApplication.translate("urbanbeatsMain", "Social Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSocial_Data.setObjectName(_fromUtf8("actionSocial_Data"))
        self.actionView_Active_Simulation_Data = QtGui.QAction(urbanbeatsMain)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/guitoolbaricons/db.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView_Active_Simulation_Data.setIcon(icon38)
        self.actionView_Active_Simulation_Data.setText(QtGui.QApplication.translate("urbanbeatsMain", "View Active Simulation Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Active_Simulation_Data.setObjectName(_fromUtf8("actionView_Active_Simulation_Data"))
        self.actionPlanning_Cycle = QtGui.QAction(urbanbeatsMain)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/cycle_planning_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlanning_Cycle.setIcon(icon39)
        self.actionPlanning_Cycle.setText(QtGui.QApplication.translate("urbanbeatsMain", "Planning Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlanning_Cycle.setObjectName(_fromUtf8("actionPlanning_Cycle"))
        self.actionImplementation_Cycle = QtGui.QAction(urbanbeatsMain)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/cycle_implement_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImplementation_Cycle.setIcon(icon40)
        self.actionImplementation_Cycle.setText(QtGui.QApplication.translate("urbanbeatsMain", "Implementation Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImplementation_Cycle.setObjectName(_fromUtf8("actionImplementation_Cycle"))
        self.actionAdd_Data_from_File = QtGui.QAction(urbanbeatsMain)
        self.actionAdd_Data_from_File.setText(QtGui.QApplication.translate("urbanbeatsMain", "Import Archive File...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Data_from_File.setObjectName(_fromUtf8("actionAdd_Data_from_File"))
        self.actionImport_Data_Archive = QtGui.QAction(urbanbeatsMain)
        self.actionImport_Data_Archive.setText(QtGui.QApplication.translate("urbanbeatsMain", "Import Archive from Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Data_Archive.setObjectName(_fromUtf8("actionImport_Data_Archive"))
        self.actionReset_Simulation = QtGui.QAction(urbanbeatsMain)
        self.actionReset_Simulation.setText(QtGui.QApplication.translate("urbanbeatsMain", "Reset Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Simulation.setObjectName(_fromUtf8("actionReset_Simulation"))
        self.actionExportDataArchive = QtGui.QAction(urbanbeatsMain)
        self.actionExportDataArchive.setText(QtGui.QApplication.translate("urbanbeatsMain", "Export Data Archive File...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportDataArchive.setObjectName(_fromUtf8("actionExportDataArchive"))
        self.actionImportProject = QtGui.QAction(urbanbeatsMain)
        self.actionImportProject.setText(QtGui.QApplication.translate("urbanbeatsMain", "Import Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportProject.setObjectName(_fromUtf8("actionImportProject"))
        self.actionExportProject = QtGui.QAction(urbanbeatsMain)
        self.actionExportProject.setText(QtGui.QApplication.translate("urbanbeatsMain", "Export Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportProject.setObjectName(_fromUtf8("actionExportProject"))
        self.actionResults_Viewer = QtGui.QAction(urbanbeatsMain)
        self.actionResults_Viewer.setText(QtGui.QApplication.translate("urbanbeatsMain", "Results Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResults_Viewer.setObjectName(_fromUtf8("actionResults_Viewer"))
        self.actionOpen_Project_Folder = QtGui.QAction(urbanbeatsMain)
        self.actionOpen_Project_Folder.setText(QtGui.QApplication.translate("urbanbeatsMain", "Open Project Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project_Folder.setObjectName(_fromUtf8("actionOpen_Project_Folder"))
        self.actionMUSIC_Model = QtGui.QAction(urbanbeatsMain)
        self.actionMUSIC_Model.setText(QtGui.QApplication.translate("urbanbeatsMain", "MUSIC Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMUSIC_Model.setObjectName(_fromUtf8("actionMUSIC_Model"))
        self.actionGoogle_Earth = QtGui.QAction(urbanbeatsMain)
        self.actionGoogle_Earth.setText(QtGui.QApplication.translate("urbanbeatsMain", "Google Earth", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoogle_Earth.setObjectName(_fromUtf8("actionGoogle_Earth"))
        self.actionSimulation_Results = QtGui.QAction(urbanbeatsMain)
        self.actionSimulation_Results.setIcon(icon4)
        self.actionSimulation_Results.setText(QtGui.QApplication.translate("urbanbeatsMain", "Simulation Results", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Results.setObjectName(_fromUtf8("actionSimulation_Results"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImportProject)
        self.menuFile.addAction(self.actionExportProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionEdit_Project_Info)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuView.addAction(self.actionProject_Description)
        self.menuView.addAction(self.actionSimulation_Results)
        self.menuAdd_GIS_Data.addAction(self.actionElevation_Data)
        self.menuAdd_GIS_Data.addAction(self.actionSoil_Data)
        self.menuAdd_GIS_Data.addAction(self.actionLand_Use)
        self.menuAdd_GIS_Data.addAction(self.actionPopulation)
        self.menuAdd_GIS_Data.addAction(self.actionPlanning)
        self.menuAdd_GIS_Data.addAction(self.actionLocality_Map)
        self.menuAdd_GIS_Data.addAction(self.actionSocial_Data)
        self.menuAdd_Climate_Data.addAction(self.actionRainfall)
        self.menuAdd_Climate_Data.addAction(self.actionEvapotranspiration)
        self.menuAdd_Climate_Data.addAction(self.actionSolar_Radiation)
        self.menuData.addAction(self.actionAddData)
        self.menuData.addAction(self.actionAdd_Data_from_File)
        self.menuData.addAction(self.actionExportDataArchive)
        self.menuData.addAction(self.actionImport_Data_Archive)
        self.menuData.addAction(self.menuAdd_GIS_Data.menuAction())
        self.menuData.addAction(self.menuAdd_Climate_Data.menuAction())
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionReset_Project_Databank)
        self.menuData.addAction(self.actionCross_check_GIS_Extents)
        self.menuData.addAction(self.actionView_Active_Simulation_Data)
        self.menuSetup_Performance_Assessment.addAction(self.actionPlanning_Cycle)
        self.menuSetup_Performance_Assessment.addAction(self.actionImplementation_Cycle)
        self.menuSimulation.addAction(self.actionSet_Spatial_Delineation)
        self.menuSimulation.addAction(self.actionDefine_Urban_Planning_Rules)
        self.menuSimulation.addAction(self.actionCustomize_Technologies)
        self.menuSimulation.addAction(self.actionTechnology_Implementation)
        self.menuSimulation.addAction(self.menuSetup_Performance_Assessment.menuAction())
        self.menuSimulation.addSeparator()
        self.menuSimulation.addAction(self.actionVerify_Simulation_Setup)
        self.menuSimulation.addAction(self.actionReset_Simulation)
        self.menuSimulation.addAction(self.actionRun_Simulation)
        self.menuFacilities.addAction(self.actionEducation)
        self.menuFacilities.addAction(self.actionCivic)
        self.menuFacilities.addAction(self.actionTransport)
        self.menuUrban_Form.addAction(self.actionResidential)
        self.menuUrban_Form.addAction(self.actionNon_Residential)
        self.menuUrban_Form.addAction(self.menuFacilities.menuAction())
        self.menuExternal_Programs.addAction(self.actionMUSIC_Model)
        self.menuExternal_Programs.addAction(self.actionGoogle_Earth)
        self.menuAdvanced.addAction(self.menuUrban_Form.menuAction())
        self.menuAdvanced.addAction(self.actionSimulation_Options)
        self.menuAdvanced.addAction(self.actionOutput_Options)
        self.menuAdvanced.addSeparator()
        self.menuAdvanced.addAction(self.menuExternal_Programs.menuAction())
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionActiveWindow)
        self.menuWindow.addAction(self.actionOpen_Project_Folder)
        self.menuWindow.addAction(self.actionResults_Viewer)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUrbanBEATS_Wiki)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionLike_on_Facebook)
        self.menuHelp.addAction(self.action_1_on_Google)
        self.menuHelp.addAction(self.actionTweet_your_activity)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionEdit_Project_Info)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAddData)
        self.toolBar.addAction(self.actionCross_check_GIS_Extents)
        self.toolBar.addAction(self.actionView_Active_Simulation_Data)
        self.toolBar.addAction(self.actionSimulation_Options)
        self.toolBar.addAction(self.actionOutput_Options)
        self.toolBar.addAction(self.actionRun_Simulation)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionProject_Description)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionUrbanBEATS_Wiki)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLike_on_Facebook)
        self.toolBar.addAction(self.action_1_on_Google)
        self.toolBar.addAction(self.actionTweet_your_activity)

        self.retranslateUi(urbanbeatsMain)
        self.simconfig_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), urbanbeatsMain.close)
        QtCore.QObject.connect(self.actionMinimize, QtCore.SIGNAL(_fromUtf8("triggered()")), urbanbeatsMain.hide)
        QtCore.QMetaObject.connectSlotsByName(urbanbeatsMain)

    def retranslateUi(self, urbanbeatsMain):
        self.simconfig_tabs.setTabText(self.simconfig_tabs.indexOf(self.tab), QtGui.QApplication.translate("urbanbeatsMain", "Base Line", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import guitoolbaricons_rc
import guitoolbaricons_rc
import guitoolbaricons_rc
import guitoolbaricons_rc
import guitoolbaricons_rc
